using Retruxel.Core.Models;
using System.Text;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Graphics;

/// <summary>
/// SMS code generator for the palette module.
/// Reads palette data from the module JSON and generates C code
/// that loads BG and sprite palettes into the SMS VDP using SMSlib.
///
/// Generated functions:
///   void palette_init(void) — loads both palettes, called once from main.
/// </summary>
public class SmsPaletteCodeGen
{
    private readonly byte[] _bgColors;
    private readonly byte[] _spriteColors;

    public SmsPaletteCodeGen(string moduleJson)
    {
        var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _bgColors = ReadByteArray(root, "bgColors", 16);
        _spriteColors = ReadByteArray(root, "spriteColors", 16);
    }

    // Validation ---------------------------------------------------------------

    /// <summary>
    /// Validates that all color values are within the SMS range (0x00–0x3F).
    /// Returns a list of warning strings — empty if valid.
    /// </summary>
    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        for (int i = 0; i < _bgColors.Length; i++)
            if (_bgColors[i] > 0x3F)
                errors.Add($"palette: BG color[{i}] = 0x{_bgColors[i]:X2} exceeds SMS maximum (0x3F).");

        for (int i = 0; i < _spriteColors.Length; i++)
            if (_spriteColors[i] > 0x3F)
                errors.Add($"palette: Sprite color[{i}] = 0x{_spriteColors[i]:X2} exceeds SMS maximum (0x3F).");

        return errors;
    }

    // Code generation ----------------------------------------------------------

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — palette module");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine("#include \"palette.h\"");
        sb.AppendLine();

        // BG palette array
        sb.AppendLine("// Background palette (16 SMS color register values, 0x00–0x3F each)");
        sb.AppendLine("const unsigned char bg_palette[16] = {");
        sb.AppendLine("    " + string.Join(", ", _bgColors.Select(c => $"0x{c:X2}")));
        sb.AppendLine("};");
        sb.AppendLine();

        // Sprite palette array
        sb.AppendLine("// Sprite palette (16 SMS color register values, 0x00–0x3F each)");
        sb.AppendLine("const unsigned char sprite_palette[16] = {");
        sb.AppendLine("    " + string.Join(", ", _spriteColors.Select(c => $"0x{c:X2}")));
        sb.AppendLine("};");
        sb.AppendLine();

        // Init function
        sb.AppendLine("void palette_init(void) {");
        sb.AppendLine("    SMS_loadBGPalette(bg_palette);");
        sb.AppendLine("    SMS_loadSpritePalette(sprite_palette);");
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = "palette.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = "palette"
        };
    }

    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — palette module");
        sb.AppendLine("#ifndef PALETTE_H");
        sb.AppendLine("#define PALETTE_H");
        sb.AppendLine();
        sb.AppendLine("extern const unsigned char bg_palette[16];");
        sb.AppendLine("extern const unsigned char sprite_palette[16];");
        sb.AppendLine();
        sb.AppendLine("void palette_init(void);");
        sb.AppendLine();
        sb.AppendLine("#endif // PALETTE_H");

        return new GeneratedFile
        {
            FileName = "palette.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = "palette"
        };
    }

    // Helpers ------------------------------------------------------------------

    private static byte[] ReadByteArray(JsonElement root, string key, int expectedLength)
    {
        var result = new byte[expectedLength];

        if (!root.TryGetProperty(key, out var arr)) return result;

        int i = 0;
        foreach (var item in arr.EnumerateArray())
        {
            if (i >= expectedLength) break;
            result[i++] = item.GetByte();
        }

        return result;
    }
}
