
using System.Text;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Graphics;

/// <summary>
/// SMS code generator for the sms.tilemap module.
/// Generates C code that loads tile graphics and a nametable layout
/// into the SMS VDP using SMSlib.
///
/// Asset data (tiles and map) are referenced as extern arrays.
/// The actual binary data comes from the asset pipeline (future Asset Manager).
/// When no asset ID is set, placeholder empty arrays are generated so the
/// project still compiles — useful during early development.
///
/// Generated functions:
///   void tilemap_init(void) — loads tiles and nametable, called once from main.
/// </summary>
public class SmsTilemapCodeGen
{
    private readonly string _tilesAssetId;
    private readonly string _mapAssetId;
    private readonly int _startTile;
    private readonly int _mapX;
    private readonly int _mapY;
    private readonly int _mapWidth;
    private readonly int _mapHeight;

    public SmsTilemapCodeGen(string moduleJson)
    {
        var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _tilesAssetId = root.TryGetProperty("tilesAssetId", out var ta) ? ta.GetString() ?? "" : "";
        _mapAssetId = root.TryGetProperty("mapAssetId", out var ma) ? ma.GetString() ?? "" : "";
        _startTile = root.TryGetProperty("startTile", out var st) ? st.GetInt32() : 0;
        _mapX = root.TryGetProperty("mapX", out var mx) ? mx.GetInt32() : 0;
        _mapY = root.TryGetProperty("mapY", out var my) ? my.GetInt32() : 0;
        _mapWidth = root.TryGetProperty("mapWidth", out var mw) ? mw.GetInt32() : 32;
        _mapHeight = root.TryGetProperty("mapHeight", out var mh) ? mh.GetInt32() : 24;
    }

    // Validation ---------------------------------------------------------------

    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        if (_startTile > 447)
            errors.Add($"sms.tilemap: startTile={_startTile} exceeds SMS VRAM limit (447).");

        if (_mapX + _mapWidth > 32)
            errors.Add($"sms.tilemap: Map extends beyond nametable width (mapX={_mapX} + mapWidth={_mapWidth} > 32).");

        if (_mapY + _mapHeight > 28)
            errors.Add($"sms.tilemap: Map extends beyond nametable height (mapY={_mapY} + mapHeight={_mapHeight} > 28).");

        if (string.IsNullOrEmpty(_tilesAssetId))
            errors.Add("sms.tilemap: No tiles asset assigned. Placeholder empty array will be used.");

        if (string.IsNullOrEmpty(_mapAssetId))
            errors.Add("sms.tilemap: No map asset assigned. Placeholder empty array will be used.");

        return errors;
    }

    // Code generation ----------------------------------------------------------

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();
        var tilesVar = string.IsNullOrEmpty(_tilesAssetId) ? "sms_tilemap_placeholder_tiles" : _tilesAssetId;
        var mapVar = string.IsNullOrEmpty(_mapAssetId) ? "sms_tilemap_placeholder_map" : _mapAssetId;
        var mapSize = _mapWidth * _mapHeight * 2; // 2 bytes per tile entry in SMS nametable

        sb.AppendLine("// Generated by Retruxel — sms.tilemap module");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine("#include \"sms_tilemap.h\"");
        sb.AppendLine();

        // Placeholder arrays when no asset is assigned
        if (string.IsNullOrEmpty(_tilesAssetId))
        {
            sb.AppendLine("// Placeholder tile data — replace with actual asset");
            sb.AppendLine("// Each SMS tile is 32 bytes (4bpp planar, 8×8 pixels)");
            sb.AppendLine("const unsigned char tilemap_placeholder_tiles[] = { 0 };");
            sb.AppendLine();
        }

        if (string.IsNullOrEmpty(_mapAssetId))
        {
            sb.AppendLine("// Placeholder nametable map — replace with actual asset");
            sb.AppendLine($"// Map is {_mapWidth}×{_mapHeight} tiles = {mapSize} bytes");
            sb.AppendLine($"const unsigned int sms_tilemap_placeholder_map[{_mapWidth * _mapHeight}] = {{ 0 }};");
            sb.AppendLine();
        }

        // Init function
        sb.AppendLine("void tilemap_init(void) {");
        sb.AppendLine($"    // Load tile graphics into VRAM starting at tile slot {_startTile}");

        if (string.IsNullOrEmpty(_tilesAssetId))
        {
            sb.AppendLine($"    // TODO: replace placeholder with: SMS_loadTiles({tilesVar}, {_startTile}, sizeof({tilesVar}));");
        }
        else
        {
            sb.AppendLine($"    SMS_loadTiles({tilesVar}, {_startTile}, sizeof({tilesVar}));");
        }

        sb.AppendLine();
        sb.AppendLine($"    // Load nametable map at position ({_mapX}, {_mapY})");

        if (string.IsNullOrEmpty(_mapAssetId))
        {
            sb.AppendLine($"    // TODO: replace placeholder with: SMS_loadTileMap({_mapX}, {_mapY}, {mapVar}, sizeof({mapVar}));");
        }
        else
        {
            sb.AppendLine($"    SMS_loadTileMap({_mapX}, {_mapY}, {mapVar}, sizeof({mapVar}));");
        }

        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = "tilemap.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = "tilemap"
        };
    }

    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — sms.tilemap module");
        sb.AppendLine("#ifndef TILEMAP_H");
        sb.AppendLine("#define TILEMAP_H");
        sb.AppendLine();
        sb.AppendLine($"#define TILEMAP_START_TILE  {_startTile}");
        sb.AppendLine($"#define TILEMAP_MAP_X       {_mapX}");
        sb.AppendLine($"#define TILEMAP_MAP_Y       {_mapY}");
        sb.AppendLine($"#define TILEMAP_MAP_WIDTH   {_mapWidth}");
        sb.AppendLine($"#define TILEMAP_MAP_HEIGHT  {_mapHeight}");
        sb.AppendLine();
        sb.AppendLine("void tilemap_init(void);");
        sb.AppendLine();
        sb.AppendLine("#endif // SMS_TILEMAP_H");

        return new GeneratedFile
        {
            FileName = "tilemap.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = "tilemap"
        };
    }
}
