using Retruxel.Core.Models;
using System.Text;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Logic;

/// <summary>
/// SMS code generator for the sms.animation module.
/// Generates C code with:
///   - An enum for animation names (ANIM_IDLE, ANIM_WALK, etc.)
///   - Frame data arrays for each animation clip
///   - State variables (current animation, current frame, frame timer)
///   - Functions to play, update and query the current animation
///
/// Generated functions:
///   void sms_animation_init(void)
///   void sms_animation_play(unsigned char animId)
///   void sms_animation_update(void)          — call each VBlank
///   unsigned char sms_animation_get_tile(void) — returns current tile index
///   unsigned char sms_animation_finished(void) — true on non-looping anims
/// </summary>
public class SmsAnimationCodeGen
{
    private readonly List<(string Name, List<int> Frames, int Speed)> _clips;

    public SmsAnimationCodeGen(string moduleJson)
    {
        _clips = [];

        var doc  = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        if (!root.TryGetProperty("animations", out var anims)) return;

        foreach (var anim in anims.EnumerateArray())
        {
            var name   = anim.TryGetProperty("name",   out var n) ? n.GetString() ?? "anim" : "anim";
            var speed  = anim.TryGetProperty("speed",  out var s) ? s.GetInt32() : 8;
            var frames = new List<int>();

            if (anim.TryGetProperty("frames", out var f))
                frames = f.EnumerateArray().Select(x => x.GetInt32()).ToList();

            _clips.Add((name, frames, speed));
        }
    }

    // Validation ---------------------------------------------------------------

    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        if (_clips.Count == 0)
            errors.Add("sms.animation: No animation clips defined.");

        foreach (var (name, frames, speed) in _clips)
        {
            if (frames.Count == 0)
                errors.Add($"sms.animation: Clip '{name}' has no frames.");
            if (speed <= 0)
                errors.Add($"sms.animation: Clip '{name}' has invalid speed ({speed}).");
        }

        return errors;
    }

    // Code generation ----------------------------------------------------------

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — sms.animation module");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("#include \"sms_animation.h\"");
        sb.AppendLine();

        // Frame count defines
        for (int i = 0; i < _clips.Count; i++)
        {
            var (name, frames, _) = _clips[i];
            sb.AppendLine($"#define ANIM_{name.ToUpper()}_FRAME_COUNT  {frames.Count}");
        }
        sb.AppendLine();

        // Frame data arrays
        sb.AppendLine("// Frame tile index arrays for each animation clip");
        for (int i = 0; i < _clips.Count; i++)
        {
            var (name, frames, _) = _clips[i];
            sb.AppendLine($"static const unsigned char anim_{name.ToLower()}_frames[] = {{");
            sb.AppendLine("    " + string.Join(", ", frames));
            sb.AppendLine("};");
        }
        sb.AppendLine();

        // Speed arrays
        sb.AppendLine("// Frame duration (VBlank count per frame) for each animation clip");
        sb.AppendLine("static const unsigned char anim_speeds[] = {");
        sb.AppendLine("    " + string.Join(", ", _clips.Select(c => c.Speed)));
        sb.AppendLine("};");
        sb.AppendLine();

        // Frame count arrays
        sb.AppendLine("// Frame count for each animation clip");
        sb.AppendLine("static const unsigned char anim_frame_counts[] = {");
        sb.AppendLine("    " + string.Join(", ", _clips.Select(c => c.Frames.Count)));
        sb.AppendLine("};");
        sb.AppendLine();

        // Pointer table
        sb.AppendLine("// Pointer table to frame arrays");
        sb.AppendLine("static const unsigned char * const anim_frames[] = {");
        foreach (var (name, _, _) in _clips)
            sb.AppendLine($"    anim_{name.ToLower()}_frames,");
        sb.AppendLine("};");
        sb.AppendLine();

        // State variables
        sb.AppendLine("// Animation state");
        sb.AppendLine("unsigned char sms_anim_current  = 0;  // current animation ID");
        sb.AppendLine("unsigned char sms_anim_frame    = 0;  // current frame index within clip");
        sb.AppendLine("unsigned char sms_anim_timer    = 0;  // VBlank counter for this frame");
        sb.AppendLine("unsigned char sms_anim_finished = 0;  // set to 1 when non-looping anim completes");
        sb.AppendLine();

        // Init
        sb.AppendLine("void sms_animation_init(void) {");
        sb.AppendLine("    sms_anim_current  = 0;");
        sb.AppendLine("    sms_anim_frame    = 0;");
        sb.AppendLine("    sms_anim_timer    = 0;");
        sb.AppendLine("    sms_anim_finished = 0;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Play — switches animation, resets frame
        sb.AppendLine("void sms_animation_play(unsigned char animId) {");
        sb.AppendLine("    if (animId == sms_anim_current) return;  // already playing");
        sb.AppendLine("    sms_anim_current  = animId;");
        sb.AppendLine("    sms_anim_frame    = 0;");
        sb.AppendLine("    sms_anim_timer    = 0;");
        sb.AppendLine("    sms_anim_finished = 0;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Update — advance frame timer
        sb.AppendLine("// Call once per VBlank to advance the animation");
        sb.AppendLine("void sms_animation_update(void) {");
        sb.AppendLine("    sms_anim_timer++;");
        sb.AppendLine("    if (sms_anim_timer >= anim_speeds[sms_anim_current]) {");
        sb.AppendLine("        sms_anim_timer = 0;");
        sb.AppendLine("        sms_anim_frame++;");
        sb.AppendLine("        if (sms_anim_frame >= anim_frame_counts[sms_anim_current]) {");
        sb.AppendLine("            sms_anim_frame    = 0;");
        sb.AppendLine("            sms_anim_finished = 1;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Get tile
        sb.AppendLine("// Returns the tile index for the current animation frame");
        sb.AppendLine("unsigned char sms_animation_get_tile(void) {");
        sb.AppendLine("    return anim_frames[sms_anim_current][sms_anim_frame];");
        sb.AppendLine("}");
        sb.AppendLine();

        // Finished flag
        sb.AppendLine("// Returns 1 if the current animation completed its last frame this update");
        sb.AppendLine("unsigned char sms_animation_finished(void) {");
        sb.AppendLine("    unsigned char f = sms_anim_finished;");
        sb.AppendLine("    sms_anim_finished = 0;  // auto-clear after read");
        sb.AppendLine("    return f;");
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName       = "sms_animation.c",
            Content        = sb.ToString(),
            FileType       = GeneratedFileType.Source,
            SourceModuleId = "sms.animation"
        };
    }

    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — sms.animation module");
        sb.AppendLine("#ifndef SMS_ANIMATION_H");
        sb.AppendLine("#define SMS_ANIMATION_H");
        sb.AppendLine();

        // Animation ID enum
        sb.AppendLine("// Animation IDs — use these with sms_animation_play()");
        sb.AppendLine("typedef enum {");
        for (int i = 0; i < _clips.Count; i++)
            sb.AppendLine($"    ANIM_{_clips[i].Name.ToUpper()} = {i},");
        sb.AppendLine($"    ANIM_COUNT = {_clips.Count}");
        sb.AppendLine("} AnimationId;");
        sb.AppendLine();

        // Extern state vars
        sb.AppendLine("extern unsigned char sms_anim_current;");
        sb.AppendLine("extern unsigned char sms_anim_frame;");
        sb.AppendLine();

        // Function declarations
        sb.AppendLine("void          sms_animation_init(void);");
        sb.AppendLine("void          sms_animation_play(unsigned char animId);");
        sb.AppendLine("void          sms_animation_update(void);");
        sb.AppendLine("unsigned char sms_animation_get_tile(void);");
        sb.AppendLine("unsigned char sms_animation_finished(void);");
        sb.AppendLine();
        sb.AppendLine("#endif // SMS_ANIMATION_H");

        return new GeneratedFile
        {
            FileName       = "sms_animation.h",
            Content        = sb.ToString(),
            FileType       = GeneratedFileType.Header,
            SourceModuleId = "sms.animation"
        };
    }
}
