using Retruxel.Core.Models;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Enemy;

/// <summary>
/// Translates the sms.enemy module JSON into SMS C code using devkitSMS.
///
/// Generated files:
///   enemy.h  — declares enemy state struct and function signatures
///   enemy.c  — initializes the enemy sprite, runs movement pattern
///              and performs AABB collision detection against the player
///
/// Requires sms.entity to be active — references the global `player` struct
/// declared in entity.h. If sms.entity is absent, the build will fail with
/// a linker error, which is the correct behavior.
///
/// Patterns:
///   Static — enemy does not move, only checks collision each frame
///   Patrol — enemy moves horizontally between x and x+patrolRange,
///            reversing direction at each boundary
///
/// Collision:
///   AABB (Axis-Aligned Bounding Box) using sprite size (8x8).
///   On collision: player.health is decremented.
///
/// devkitSMS functions used:
///   SMS_addSprite(x, y, tile) — adds sprite to SAT (called after entity_update)
/// </summary>
public class SmsEnemyCodeGen
{
    private readonly int    _spriteId;
    private readonly int    _x;
    private readonly int    _y;
    private readonly int    _speed;
    private readonly int    _health;
    private readonly string _pattern;
    private readonly int    _patrolRange;

    private const int ScreenWidth  = 256;
    private const int ScreenHeight = 192;
    private const int SpriteSize   = 8;

    public SmsEnemyCodeGen(string moduleJson)
    {
        using var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _spriteId    = root.TryGetProperty("spriteId",    out var s)  ? s.GetInt32()    : 1;
        _x           = root.TryGetProperty("x",           out var x)  ? x.GetInt32()    : 120;
        _y           = root.TryGetProperty("y",           out var y)  ? y.GetInt32()    : 144;
        _speed       = root.TryGetProperty("speed",       out var sp) ? sp.GetInt32()   : 1;
        _health      = root.TryGetProperty("health",      out var h)  ? h.GetInt32()    : 1;
        _pattern     = root.TryGetProperty("pattern",     out var p)  ? p.GetString() ?? "Patrol" : "Patrol";
        _patrolRange = root.TryGetProperty("patrolRange", out var pr) ? pr.GetInt32()   : 64;
    }

    public IEnumerable<string> Validate()
    {
        if (_x < 0 || _x >= ScreenWidth)
            yield return $"sms.enemy: x={_x} is out of range (0–{ScreenWidth - 1})";
        if (_y < 0 || _y >= ScreenHeight)
            yield return $"sms.enemy: y={_y} is out of range (0–{ScreenHeight - 1})";
        if (_x + _patrolRange > ScreenWidth)
            yield return $"sms.enemy: patrol range exceeds screen width " +
                         $"(x={_x} + patrolRange={_patrolRange} > {ScreenWidth})";
    }

    public GeneratedFile GenerateHeader() => new()
    {
        FileName       = "enemy.h",
        FileType       = GeneratedFileType.Header,
        SourceModuleId = "sms.enemy",
        Content        = """
            // Generated by Retruxel — sms.enemy module. Do not edit manually.
            #ifndef ENEMY_H
            #define ENEMY_H

            #include "entity.h"

            typedef struct {
                int x;
                int y;
                int speed;
                int health;
                int spriteId;
                int direction;      /* 1 = right, -1 = left */
                int patrolOrigin;
                int patrolRange;
            } Enemy;

            void sms_enemy_init(void);
            void sms_enemy_update(void);

            #endif // ENEMY_H
            """
    };

    public GeneratedFile GenerateCode()
    {
        var movementCode = _pattern == "Patrol"
            ? $$"""
                    /* Patrol movement */
                    enemy.x += enemy.speed * enemy.direction;

                    if (enemy.x >= enemy.patrolOrigin + enemy.patrolRange) {
                        enemy.x         = enemy.patrolOrigin + enemy.patrolRange;
                        enemy.direction = -1;
                    }
                    if (enemy.x <= enemy.patrolOrigin) {
                        enemy.x         = enemy.patrolOrigin;
                        enemy.direction = 1;
                    }
               """
            : "    /* Static pattern — no movement */";

        return new GeneratedFile
        {
            FileName       = "enemy.c",
            FileType       = GeneratedFileType.Source,
            SourceModuleId = "sms.enemy",
            Content        = $$"""
                // Generated by Retruxel — sms.enemy module. Do not edit manually.
                // Pattern: {{_pattern}} | Speed: {{_speed}}px/frame
                #include "SMSlib.h"
                #include "enemy.h"

                static Enemy enemy;

                void sms_enemy_init(void) {
                    enemy.x            = {{_x}};
                    enemy.y            = {{_y}};
                    enemy.speed        = {{_speed}};
                    enemy.health       = {{_health}};
                    enemy.spriteId     = {{_spriteId}};
                    enemy.direction    = 1;
                    enemy.patrolOrigin = {{_x}};
                    enemy.patrolRange  = {{_patrolRange}};
                }

                void sms_enemy_update(void) {
                    if (enemy.health <= 0) return;

                {{movementCode}}

                    /* AABB collision against player (8x8 sprites) */
                    if (enemy.x < player.x + {{SpriteSize}} &&
                        enemy.x + {{SpriteSize}} > player.x &&
                        enemy.y < player.y + {{SpriteSize}} &&
                        enemy.y + {{SpriteSize}} > player.y) {
                        player.health--;
                    }

                    SMS_addSprite(enemy.x, enemy.y, enemy.spriteId);
                }
                """
        };
    }
}
