using Retruxel.Core.Models;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Entity;

/// <summary>
/// Translates the sms.entity module JSON into SMS C code using devkitSMS.
///
/// Generated files:
///   entity.h  — declares entity state struct and function signatures
///   entity.c  — initializes the player sprite and processes input each frame
///
/// The player struct is globally accessible so sms.enemy can reference it
/// for collision detection.
///
/// devkitSMS functions used:
///   SMS_addSprite(x, y, tile)     — adds a sprite to the SAT
///   SMS_initSprites()             — clears the SAT before adding sprites
///   SMS_copySpritestoSAT()        — flushes the SAT to VRAM
///   SMS_getKeysStatus()           — reads joypad state
///   PORT_A_KEY_LEFT/RIGHT/UP/DOWN — direction constants
/// </summary>
public class SmsEntityCodeGen
{
    private readonly int _spriteId;
    private readonly int _x;
    private readonly int _y;
    private readonly int _speed;
    private readonly int _health;

    private const int ScreenWidth  = 256;
    private const int ScreenHeight = 192;
    private const int SpriteSize   = 8;

    public SmsEntityCodeGen(string moduleJson)
    {
        using var doc  = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _spriteId = root.TryGetProperty("spriteId", out var s) ? s.GetInt32() : 0;
        _x        = root.TryGetProperty("x",        out var x) ? x.GetInt32() : 32;
        _y        = root.TryGetProperty("y",        out var y) ? y.GetInt32() : 144;
        _speed    = root.TryGetProperty("speed",    out var sp) ? sp.GetInt32() : 2;
        _health   = root.TryGetProperty("health",   out var h) ? h.GetInt32() : 3;
    }

    public IEnumerable<string> Validate()
    {
        if (_x < 0 || _x >= ScreenWidth)
            yield return $"sms.entity: x={_x} is out of range (0–{ScreenWidth - 1})";
        if (_y < 0 || _y >= ScreenHeight)
            yield return $"sms.entity: y={_y} is out of range (0–{ScreenHeight - 1})";
        if (_speed < 1 || _speed > 8)
            yield return $"sms.entity: speed={_speed} is out of range (1–8)";
    }

    public GeneratedFile GenerateHeader() => new()
    {
        FileName       = "entity.h",
        FileType       = GeneratedFileType.Header,
        SourceModuleId = "sms.entity",
        Content        = """
            // Generated by Retruxel — sms.entity module. Do not edit manually.
            #ifndef ENTITY_H
            #define ENTITY_H

            typedef struct {
                int x;
                int y;
                int speed;
                int health;
                int spriteId;
            } Player;

            // Global player instance — accessible by sms.enemy for collision
            extern Player player;

            void sms_entity_init(void);
            void sms_entity_update(void);

            #endif // ENTITY_H
            """
    };

    public GeneratedFile GenerateCode() => new()
    {
        FileName       = "entity.c",
        FileType       = GeneratedFileType.Source,
        SourceModuleId = "sms.entity",
        Content        = $$"""
            // Generated by Retruxel — sms.entity module. Do not edit manually.
            #include "SMSlib.h"
            #include "entity.h"

            Player player;

            void sms_entity_init(void) {
                player.x        = {{_x}};
                player.y        = {{_y}};
                player.speed    = {{_speed}};
                player.health   = {{_health}};
                player.spriteId = {{_spriteId}};
            }

            void sms_entity_update(void) {
                unsigned int keys = SMS_getKeysStatus();

                if (keys & PORT_A_KEY_LEFT)  player.x -= player.speed;
                if (keys & PORT_A_KEY_RIGHT) player.x += player.speed;
                if (keys & PORT_A_KEY_UP)    player.y -= player.speed;
                if (keys & PORT_A_KEY_DOWN)  player.y += player.speed;

                /* Clamp to screen bounds */
                if (player.x < 0)                           player.x = 0;
                if (player.x > {{ScreenWidth - SpriteSize}})  player.x = {{ScreenWidth - SpriteSize}};
                if (player.y < 0)                           player.y = 0;
                if (player.y > {{ScreenHeight - SpriteSize}}) player.y = {{ScreenHeight - SpriteSize}};

                SMS_initSprites();
                SMS_addSprite(player.x, player.y, player.spriteId);
                SMS_copySpritestoSAT();
            }
            """
    };
}
