<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Retruxel.SDK\Retruxel.SDK.csproj" />
		<ProjectReference Include="..\Retruxel.Lib.PaletteHelpers\Retruxel.Lib.PaletteHelpers.csproj" />
		<ProjectReference Include="..\Retruxel.Lib.TilesetHelpers\Retruxel.Lib.TilesetHelpers.csproj" />
		<ProjectReference Include="..\Retruxel.Lib.WPFImageProcessing\Retruxel.Lib.WPFImageProcessing.csproj" />
		<ProjectReference Include="..\Retruxel.Tool.AssetImporter\Retruxel.Tool.AssetImporter.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\Retruxel.Tool.AssetProcessor\Retruxel.Tool.AssetProcessor.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\Retruxel.Tool.TilePacker\Retruxel.Tool.TilePacker.csproj" />
		<ProjectReference Include="..\Retruxel.Tool.PaletteEditor\Retruxel.Tool.PaletteEditor.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	<Target Name="CopyToRetruxelOutput" AfterTargets="Build">
		<PropertyGroup>
			<RetruxelOutput>..\..\..\Retruxel\bin\$(Configuration)\net10.0-windows\Plugins\Tools\</RetruxelOutput>
		</PropertyGroup>
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(RetruxelOutput)" />
	</Target>

</Project>
