using Retruxel.Core.Models;
using System.Text;

namespace Retruxel.Target.SMS.Modules.Splash;

/// <summary>
/// Generates the "MADE WITH RETRUXEL" splash screen C code for the SMS.
///
/// The splash displays a 144×112 pixel image centered on the 256×192 screen,
/// using a full palette fade-in and fade-out effect via VDP palette manipulation.
///
/// Technique — palette fade on SMS:
///   The SMS VDP has no hardware fade. We simulate it by loading the image with
///   a black palette and incrementally stepping each color channel toward its
///   target value over N VBlanks. On fade-out we reverse the process.
///
///   Each SMS color byte is 0bBBGGRR (2 bits per channel, values 0–3).
///   Step size = 1 per channel per frame → full fade in 3 frames minimum.
///   We use FADE_STEPS=8 frames for a smooth visible effect.
///
/// Timing (all at 60fps NTSC):
///   Fade in:  SPLASH_FADE_FRAMES (30 frames = 0.5s)
///   Hold:     SPLASH_HOLD_FRAMES (60 frames = 1.0s)
///   Fade out: SPLASH_FADE_FRAMES (30 frames = 0.5s)
///   Total:    ~2 seconds
///
/// Generated files:
///   sms_splash.h — declarations
///   sms_splash.c — tile data, palette, fade logic, show/hide functions
/// </summary>
public class SmsSplashCodeGen
{
    // Timing constants (frames at 60fps)
    private const int FadeFrames = 30;
    private const int HoldFrames = 60;

    // SMS screen and image dimensions
    private const int ScreenTilesX = 32;
    private const int ScreenTilesY = 24;
    private const int ImagePixelsX = 144;
    private const int ImagePixelsY = 112;
    private const int ImageTilesX  = ImagePixelsX / 8; // 18
    private const int ImageTilesY  = ImagePixelsY / 8; // 14

    // Centered position in the nametable
    private const int OffsetTileX  = (ScreenTilesX - ImageTilesX) / 2; // 7
    private const int OffsetTileY  = (ScreenTilesY - ImageTilesY) / 2; // 5

    public GeneratedFile GenerateHeader() => new()
    {
        FileName       = "sms_splash.h",
        FileType       = GeneratedFileType.Header,
        SourceModuleId = "retruxel.splash",
        Content        = """
            // Generated by Retruxel — MADE WITH RETRUXEL splash screen.
            // Do not edit manually.
            #ifndef SMS_SPLASH_H
            #define SMS_SPLASH_H

            // Display the splash screen and block until complete (~2 seconds).
            // Call this as the very first thing in main(), before any module init.
            void sms_splash_show(void);

            #endif // SMS_SPLASH_H
            """
    };

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — MADE WITH RETRUXEL splash screen.");
        sb.AppendLine("// Do not edit manually.");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine("#include \"sms_splash.h\"");
        sb.AppendLine();

        // Timing defines
        sb.AppendLine($"#define SPLASH_FADE_FRAMES  {FadeFrames}");
        sb.AppendLine($"#define SPLASH_HOLD_FRAMES  {HoldFrames}");
        sb.AppendLine($"#define SPLASH_IMAGE_TILES  {ImageTilesX * ImageTilesY}");
        sb.AppendLine($"#define SPLASH_OFFSET_X     {OffsetTileX}");
        sb.AppendLine($"#define SPLASH_OFFSET_Y     {OffsetTileY}");
        sb.AppendLine();

        // Tile data — placeholder until real image is converted
        // Each SMS tile = 32 bytes (8x8 pixels, 4bpp planar)
        // TODO: replace with actual converted tile data from the splash image
        sb.AppendLine("// Splash screen tile graphics (4bpp planar, 8x8 per tile)");
        sb.AppendLine("// PLACEHOLDER — replace with actual tile data");
        sb.AppendLine($"static const unsigned char splash_tiles[{ImageTilesX * ImageTilesY} * 32] = {{");
        sb.AppendLine("    /* tile data will be generated here */");
        sb.AppendLine("    0");
        sb.AppendLine("};");
        sb.AppendLine();

        // Nametable — which tile index to place at each position
        sb.AppendLine("// Nametable entries for the splash image");
        sb.AppendLine($"static const unsigned int splash_map[{ImageTilesX * ImageTilesY}] = {{");
        var mapEntries = new List<string>();
        for (int i = 0; i < ImageTilesX * ImageTilesY; i++)
            mapEntries.Add(i.ToString());
        sb.AppendLine("    " + string.Join(", ", mapEntries));
        sb.AppendLine("};");
        sb.AppendLine();

        // Target palette — full brightness colors for the splash image
        // PLACEHOLDER — replace with actual colors extracted from the image
        sb.AppendLine("// Target palette (full brightness — faded in from black)");
        sb.AppendLine("// PLACEHOLDER — replace with actual palette from splash image");
        sb.AppendLine("static const unsigned char splash_palette_target[32] = {");
        sb.AppendLine("    /* BG palette (16 entries) */");
        sb.AppendLine("    0x00, 0x3F, 0x15, 0x2A, 0x05, 0x0A, 0x0F, 0x14,");
        sb.AppendLine("    0x19, 0x1E, 0x23, 0x28, 0x2D, 0x32, 0x37, 0x3C,");
        sb.AppendLine("    /* Sprite palette (16 entries — unused, kept for safety) */");
        sb.AppendLine("    0x00, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,");
        sb.AppendLine("    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00");
        sb.AppendLine("};");
        sb.AppendLine();

        // Working palette buffer (faded toward target)
        sb.AppendLine("// Working palette buffer — starts at 0 (black), fades to target");
        sb.AppendLine("static unsigned char splash_palette_current[32];");
        sb.AppendLine();

        // Fade helpers
        sb.AppendLine("// Steps a single SMS color byte toward its target.");
        sb.AppendLine("// SMS color format: 0bBBGGRR — 2 bits per channel.");
        sb.AppendLine("// step > 0 = fade in, step < 0 = fade out.");
        sb.AppendLine("static unsigned char splash_step_color(unsigned char current, unsigned char target, signed char step) {");
        sb.AppendLine("    unsigned char rr_cur = (current     ) & 0x03;");
        sb.AppendLine("    unsigned char gg_cur = (current >> 2) & 0x03;");
        sb.AppendLine("    unsigned char bb_cur = (current >> 4) & 0x03;");
        sb.AppendLine("    unsigned char rr_tgt = (target     ) & 0x03;");
        sb.AppendLine("    unsigned char gg_tgt = (target >> 2) & 0x03;");
        sb.AppendLine("    unsigned char bb_tgt = (target >> 4) & 0x03;");
        sb.AppendLine("    if (step > 0) {");
        sb.AppendLine("        if (rr_cur < rr_tgt) rr_cur++;");
        sb.AppendLine("        if (gg_cur < gg_tgt) gg_cur++;");
        sb.AppendLine("        if (bb_cur < bb_tgt) bb_cur++;");
        sb.AppendLine("    } else {");
        sb.AppendLine("        if (rr_cur > 0) rr_cur--;");
        sb.AppendLine("        if (gg_cur > 0) gg_cur--;");
        sb.AppendLine("        if (bb_cur > 0) bb_cur--;");
        sb.AppendLine("    }");
        sb.AppendLine("    return (bb_cur << 4) | (gg_cur << 2) | rr_cur;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Fade step — advance all 32 palette entries one step
        sb.AppendLine("// Advance the entire palette one step toward target (fade in)");
        sb.AppendLine("// or toward black (fade out).");
        sb.AppendLine("static void splash_fade_step(signed char direction) {");
        sb.AppendLine("    unsigned char i;");
        sb.AppendLine("    unsigned char tgt;");
        sb.AppendLine("    for (i = 0; i < 32; i++) {");
        sb.AppendLine("        tgt = (direction > 0) ? splash_palette_target[i] : 0;");
        sb.AppendLine("        splash_palette_current[i] = splash_step_color(");
        sb.AppendLine("            splash_palette_current[i], tgt, direction);");
        sb.AppendLine("    }");
        sb.AppendLine("    SMS_loadBGPalette(splash_palette_current);");
        sb.AppendLine("    SMS_loadSpritePalette(splash_palette_current + 16);");
        sb.AppendLine("}");
        sb.AppendLine();

        // Main show function
        sb.AppendLine("void sms_splash_show(void) {");
        sb.AppendLine("    unsigned char i;");
        sb.AppendLine();
        sb.AppendLine("    // Clear screen and load splash tiles into VRAM");
        sb.AppendLine("    SMS_VRAMmemsetW(0, 0x0000, 16384);");
        sb.AppendLine($"    SMS_loadTiles(splash_tiles, 0, sizeof(splash_tiles));");
        sb.AppendLine();
        sb.AppendLine("    // Load nametable centered on screen");
        sb.AppendLine($"    SMS_loadTileMap({OffsetTileX}, {OffsetTileY}, splash_map, sizeof(splash_map));");
        sb.AppendLine();
        sb.AppendLine("    // Start with black palette");
        sb.AppendLine("    for (i = 0; i < 32; i++) splash_palette_current[i] = 0;");
        sb.AppendLine("    SMS_loadBGPalette(splash_palette_current);");
        sb.AppendLine("    SMS_loadSpritePalette(splash_palette_current + 16);");
        sb.AppendLine();
        sb.AppendLine("    SMS_displayOn();");
        sb.AppendLine();
        sb.AppendLine("    // Fade in");
        sb.AppendLine("    for (i = 0; i < SPLASH_FADE_FRAMES; i++) {");
        sb.AppendLine("        SMS_waitForVBlank();");
        sb.AppendLine("        splash_fade_step(1);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Hold");
        sb.AppendLine("    for (i = 0; i < SPLASH_HOLD_FRAMES; i++) {");
        sb.AppendLine("        SMS_waitForVBlank();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Fade out");
        sb.AppendLine("    for (i = 0; i < SPLASH_FADE_FRAMES; i++) {");
        sb.AppendLine("        SMS_waitForVBlank();");
        sb.AppendLine("        splash_fade_step(-1);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Clean up — clear VRAM and turn display off before game init");
        sb.AppendLine("    SMS_displayOff();");
        sb.AppendLine("    SMS_VRAMmemsetW(0, 0x0000, 16384);");
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName       = "sms_splash.c",
            FileType       = GeneratedFileType.Source,
            SourceModuleId = "retruxel.splash",
            Content        = sb.ToString()
        };
    }
}
