using Retruxel.Core.Models;
using System.Text;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Graphics;

/// <summary>
/// SMS code generator for the sms.sprite module.
/// Generates C code that:
///   1. Loads sprite tile graphics into VRAM
///   2. Initializes the SMS Sprite Attribute Table (SAT)
///   3. Provides functions to add sprites and flush the SAT each frame
///
/// The SMS SAT supports up to 64 sprite entries.
/// Sprites are 8×8 or 8×16 depending on the VDP mode set.
///
/// Generated functions:
///   void sms_sprite_init(void)                           — called once from main
///   void sms_sprite_begin(void)                          — call at start of each frame
///   void sms_sprite_add(unsigned char x, unsigned char y, unsigned char tile)
///   void sms_sprite_flush(void)                          — call after adding all sprites
/// </summary>
public class SmsSpriteCodeGen
{
    private readonly string _tilesAssetId;
    private readonly int _startTile;
    private readonly bool _doubleHeight;

    public SmsSpriteCodeGen(string moduleJson)
    {
        var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _tilesAssetId = root.TryGetProperty("tilesAssetId", out var ta) ? ta.GetString() ?? "" : "";
        _startTile = root.TryGetProperty("startTile", out var st) ? st.GetInt32() : 256;
        _doubleHeight = root.TryGetProperty("doubleHeight", out var dh) && dh.GetBoolean();
    }

    // Validation ---------------------------------------------------------------

    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        if (_startTile > 511)
            errors.Add($"sms.sprite: startTile={_startTile} exceeds SMS VRAM limit (511).");

        if (string.IsNullOrEmpty(_tilesAssetId))
            errors.Add("sms.sprite: No tiles asset assigned. Placeholder empty array will be used.");

        return errors;
    }

    // Code generation ----------------------------------------------------------

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();
        var tilesVar = string.IsNullOrEmpty(_tilesAssetId) ? "sms_sprite_placeholder_tiles" : _tilesAssetId;

        sb.AppendLine("// Generated by Retruxel — sms.sprite module");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine("#include \"sms_sprite.h\"");
        sb.AppendLine();

        // Placeholder tile data when no asset assigned
        if (string.IsNullOrEmpty(_tilesAssetId))
        {
            sb.AppendLine("// Placeholder sprite tile data — replace with actual asset");
            sb.AppendLine("const unsigned char sms_sprite_placeholder_tiles[] = { 0 };");
            sb.AppendLine();
        }

        // Init function
        sb.AppendLine("void sms_sprite_init(void) {");

        if (_doubleHeight)
        {
            sb.AppendLine("    // Enable 8x16 double-height sprite mode");
            sb.AppendLine("    SMS_VDPturnOnFeature(FEATURE_SPRITES_8x16);");
        }

        sb.AppendLine();

        // Sprite tiles go in the second half of VRAM by default
        sb.AppendLine($"    // Load sprite tile graphics into VRAM at tile slot {_startTile}");
        sb.AppendLine($"    // Sprite tiles use the second half of VRAM (tiles {_startTile}+)");

        if (string.IsNullOrEmpty(_tilesAssetId))
        {
            sb.AppendLine($"    // TODO: replace placeholder with: SMS_loadTiles({tilesVar}, {_startTile}, sizeof({tilesVar}));");
        }
        else
        {
            sb.AppendLine($"    SMS_loadTiles({tilesVar}, {_startTile}, sizeof({tilesVar}));");
        }

        // Use first or second half of VRAM for sprites
        if (_startTile >= 256)
        {
            sb.AppendLine();
            sb.AppendLine("    // Use second half of VRAM (tiles 256-511) for sprites");
            sb.AppendLine("    SMS_useFirstHalfTilesforSprites(0);");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine("    // Use first half of VRAM (tiles 0-255) for sprites");
            sb.AppendLine("    SMS_useFirstHalfTilesforSprites(1);");
        }

        sb.AppendLine();
        sb.AppendLine("    SMS_initSprites();");
        sb.AppendLine("    SMS_copySpritestoSAT();");
        sb.AppendLine("}");
        sb.AppendLine();

        // Begin frame — clear SAT
        sb.AppendLine("// Call at the beginning of each frame to clear the sprite list");
        sb.AppendLine("void sms_sprite_begin(void) {");
        sb.AppendLine("    SMS_initSprites();");
        sb.AppendLine("}");
        sb.AppendLine();

        // Add sprite
        sb.AppendLine("// Add a sprite to the SAT. tile is relative to startTile.");
        sb.AppendLine("void sms_sprite_add(unsigned char x, unsigned char y, unsigned char tile) {");
        sb.AppendLine($"    SMS_addSprite(x, y, tile + {_startTile % 256});");
        sb.AppendLine("}");
        sb.AppendLine();

        // Flush SAT to VRAM
        sb.AppendLine("// Call after adding all sprites to push the SAT to VRAM");
        sb.AppendLine("void sms_sprite_flush(void) {");
        sb.AppendLine("    SMS_copySpritestoSAT();");
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = "sms_sprite.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = "sms.sprite"
        };
    }

    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — sms.sprite module");
        sb.AppendLine("#ifndef SMS_SPRITE_H");
        sb.AppendLine("#define SMS_SPRITE_H");
        sb.AppendLine();
        sb.AppendLine($"#define SPRITE_START_TILE    {_startTile}");
        sb.AppendLine($"#define SPRITE_DOUBLE_HEIGHT {(_doubleHeight ? 1 : 0)}");
        sb.AppendLine();
        sb.AppendLine("void sms_sprite_init(void);");
        sb.AppendLine("void sms_sprite_begin(void);");
        sb.AppendLine("void sms_sprite_add(unsigned char x, unsigned char y, unsigned char tile);");
        sb.AppendLine("void sms_sprite_flush(void);");
        sb.AppendLine();
        sb.AppendLine("#endif // SMS_SPRITE_H");

        return new GeneratedFile
        {
            FileName = "sms_sprite.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = "sms.sprite"
        };
    }
}
