using Retruxel.Core.Models;

namespace Retruxel.Core.Interfaces;

/// <summary>
/// Contract for all audio modules.
/// Audio modules handle music composition and sound effects
/// targeting the specific sound chip of each console.
/// Each target implements this interface for its own audio hardware.
/// Ex: SN76489 (SMS/Game Gear), 2A03 (NES), SPC700 (SNES).
/// </summary>
public interface IAudioModule : IModule
{
    /// <summary>
    /// Name of the target sound chip.
    /// Ex: "SN76489", "2A03", "SPC700"
    /// </summary>
    string ChipName { get; }

    /// <summary>Number of tone channels available on the target chip.</summary>
    int ToneChannels { get; }

    /// <summary>Number of noise channels available on the target chip.</summary>
    int NoiseChannels { get; }

    /// <summary>
    /// Returns the ViewModel for this module's audio editor.
    /// Typically a sequencer, tracker or piano roll ViewModel.
    /// The shell binds this to a WPF View.
    /// </summary>
    object CreateEditorViewModel();

    /// <summary>
    /// Returns all C source files generated by this module.
    /// Includes music data tables and the playback driver.
    /// </summary>
    IEnumerable<GeneratedFile> GenerateCode();

    /// <summary>
    /// Returns all binary audio asset files generated by this module.
    /// Ex: VGM data, PSG register tables.
    /// </summary>
    IEnumerable<GeneratedAsset> GenerateAssets();
}