using Retruxel.Core.Models;

namespace Retruxel.Core.Interfaces;

/// <summary>
/// Contract for all graphic modules.
/// Graphic modules handle visual assets — tiles, sprites, palettes, tilemaps.
/// The host shell uses CreateEditorViewModel() to build the UI dynamically,
/// keeping WPF dependencies out of the Core library.
/// </summary>
public interface IGraphicModule : IModule
{
    /// <summary>
    /// Returns the ViewModel for this module's visual editor.
    /// The shell is responsible for binding this ViewModel to a WPF View.
    /// This keeps WPF dependencies out of Retruxel.Core.
    /// </summary>
    object CreateEditorViewModel();

    /// <summary>
    /// Returns all C source files generated by this module.
    /// Called by the CodeGenerator during the build pipeline.
    /// </summary>
    IEnumerable<GeneratedFile> GenerateCode();

    /// <summary>
    /// Returns all binary asset files generated by this module.
    /// Ex: tile data arrays, palette tables.
    /// </summary>
    IEnumerable<GeneratedAsset> GenerateAssets();
}