using Retruxel.Core.Models;

namespace Retruxel.Core.Interfaces;

/// <summary>
/// Contract for all logic modules.
/// Logic modules handle gameplay behavior — physics, input, entities, sound.
/// Unlike graphic modules, they do not render a visual editor directly;
/// their UI is auto-generated by the shell from the ModuleManifest.
/// </summary>
public interface ILogicModule : IModule
{
    /// <summary>
    /// Returns the manifest describing this module's parameters.
    /// The shell reads this to auto-generate the configuration UI.
    /// </summary>
    ModuleManifest GetManifest();

    /// <summary>
    /// Returns all C source files generated by this module.
    /// Called by the CodeGenerator during the build pipeline.
    /// </summary>
    IEnumerable<GeneratedFile> GenerateCode();
}