using Retruxel.Core.Interfaces;
using Retruxel.Core.Models;

namespace Retruxel.Core.Services;

/// <summary>
/// Orchestrates code generation across all active modules in a project.
/// Collects generated files and assets from each module and assembles
/// a BuildContext ready for the IToolchain to compile.
/// </summary>
public class CodeGenerator
{
    private readonly ModuleLoader _moduleLoader;

    public CodeGenerator(ModuleLoader moduleLoader)
    {
        _moduleLoader = moduleLoader;
    }

    /// <summary>
    /// Generates all source files and assets for the given project.
    /// Returns a BuildContext ready to be passed to IToolchain.BuildAsync.
    /// </summary>
    public async Task<BuildContext> GenerateAsync(
        RetruxelProject project,
        IProgress<string>? progress = null)
    {
        var sourceFiles = new List<GeneratedFile>();
        var assets = new List<GeneratedAsset>();

        progress?.Report("INIT: Starting code generation...");

        foreach (var moduleId in project.DefaultModules)
        {
            progress?.Report($"PROC: Generating module {moduleId}...");

            // Graphic modules
            if (_moduleLoader.GraphicModules.TryGetValue(moduleId, out var graphicModule))
            {
                sourceFiles.AddRange(graphicModule.GenerateCode());
                assets.AddRange(graphicModule.GenerateAssets());
                continue;
            }

            // Logic modules
            if (_moduleLoader.LogicModules.TryGetValue(moduleId, out var logicModule))
            {
                sourceFiles.AddRange(logicModule.GenerateCode());
                continue;
            }

            // Audio modules
            if (_moduleLoader.AudioModules.TryGetValue(moduleId, out var audioModule))
            {
                sourceFiles.AddRange(audioModule.GenerateCode());
                assets.AddRange(audioModule.GenerateAssets());
                continue;
            }

            progress?.Report($"WARN: Module {moduleId} not found — skipping.");
        }

        // Generate the main entry point that includes all module headers
        var mainFile = GenerateMainFile(project, sourceFiles);
        sourceFiles.Insert(0, mainFile);

        progress?.Report($"INFO: {sourceFiles.Count} source files generated.");
        progress?.Report($"INFO: {assets.Count} assets generated.");

        var outputDir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
            "Retruxel", "builds", Guid.NewGuid().ToString());

        return new BuildContext
        {
            TargetId = project.TargetId,
            SourceFiles = sourceFiles,
            Assets = assets,
            OutputDirectory = outputDir,
            BuildParameters = project.Parameters
                .Where(p => p.Key.StartsWith("target."))
                .ToDictionary(p => p.Key.Replace("target.", ""), p => p.Value)
        };
    }

    /// <summary>
    /// Generates the main.c entry point that includes all module headers
    /// and calls their initialization functions.
    /// </summary>
    private GeneratedFile GenerateMainFile(
        RetruxelProject project,
        IEnumerable<GeneratedFile> generatedFiles)
    {
        var headers = generatedFiles
            .Where(f => f.FileType == GeneratedFileType.Header)
            .Select(f => $"#include \"{f.FileName}\"");

        var content = string.Join("\n", [
            "// Generated by Retruxel — do not edit manually.",
            $"// Project: {project.Name} | Target: {project.TargetId}",
            $"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}",
            "",
            .. headers,
            "",
            "void main(void) {",
            "    // Module initialization — generated by Retruxel",
            "}"
        ]);

        return new GeneratedFile
        {
            FileName = "main.c",
            Content = content,
            FileType = GeneratedFileType.Source,
            SourceModuleId = "retruxel.core"
        };
    }
}