using System;
using System.Collections.Generic;

namespace Retruxel.Core.Models;

/// <summary>
/// Contains all data required by the toolchain to perform a build.
/// Assembled by the CodeGenerator and passed to IToolchain.BuildAsync.
/// </summary>
public class BuildContext
{
    /// <summary>
    /// Unique identifier for this build run.
    /// Used to create an isolated output folder.
    /// </summary>
    public string BuildId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Target identifier for this build. Ex: "sms", "nes"</summary>
    public string TargetId { get; set; } = string.Empty;

    /// <summary>
    /// All C source files generated by the project's modules.
    /// The toolchain compiles these into the final ROM.
    /// </summary>
    public IEnumerable<GeneratedFile> SourceFiles { get; set; } = [];

    /// <summary>
    /// All binary assets generated by the project's modules.
    /// The toolchain includes these in the ROM build.
    /// </summary>
    public IEnumerable<GeneratedAsset> Assets { get; set; } = [];

    /// <summary>
    /// Target-specific build parameters.
    /// Ex: ROM size, region, mapper settings.
    /// Key is the parameter name, value is the parameter value.
    /// </summary>
    public Dictionary<string, object> BuildParameters { get; set; } = new();

    /// <summary>
    /// Output directory where the ROM and build artifacts will be written.
    /// Defaults to %AppData%\Retruxel\builds\{BuildId}\
    /// </summary>
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>
    /// Build diagnostics report generated by the target.
    /// Contains hardware usage metrics (VRAM, RAM, ROM, sprites, etc.)
    /// Null if target does not support diagnostics.
    /// </summary>
    public BuildDiagnosticsReport? Diagnostics { get; set; }

    /// <summary>
    /// Incremental build plan generated by CodeGenerator.
    /// Toolchains use it to skip unchanged writes and source compilation.
    /// </summary>
    public IncrementalBuildInfo? IncrementalBuild { get; set; }
}

/// <summary>
/// Hash-based cache state for an incremental build run.
/// </summary>
public class IncrementalBuildInfo
{
    public int Version { get; set; } = 1;
    public bool Enabled { get; set; } = true;
    public bool HasPreviousCache { get; set; }
    public bool HeaderChanged { get; set; }
    public string TargetId { get; set; } = string.Empty;
    public string ManifestPath { get; set; } = string.Empty;
    public Dictionary<string, string> SourceHashes { get; set; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, string> AssetHashes { get; set; } = new(StringComparer.OrdinalIgnoreCase);
    public List<string> ChangedSourceFiles { get; set; } = [];
    public List<string> ChangedAssetFiles { get; set; } = [];
    public List<string> RemovedSourceFiles { get; set; } = [];
    public List<string> RemovedAssetFiles { get; set; } = [];
}
