namespace Retruxel.Core.Models;

/// <summary>
/// Represents a C source file generated by a module during the build pipeline.
/// </summary>
public class GeneratedFile
{
    /// <summary>
    /// File name including extension. Ex: "physics.c", "tiles.h"
    /// </summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Full generated C source content.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// File type — determines how the CodeGenerator handles it.
    /// </summary>
    public GeneratedFileType FileType { get; set; }

    /// <summary>
    /// The module that generated this file.
    /// Used for error reporting in the ToolchainValidator.
    /// </summary>
    public string SourceModuleId { get; set; } = string.Empty;

    /// <summary>
    /// The element ID that generated this file (for scene-specific modules).
    /// Used to track which scene a file belongs to.
    /// </summary>
    public string? SourceElementId { get; set; }

    /// <summary>
    /// The scene ID that this file belongs to (for scene-specific modules).
    /// Used to filter files when generating scene init functions.
    /// </summary>
    public string? SourceSceneId { get; set; }

    /// <summary>
    /// The ROM bank this file belongs to. Matches a RomBank.Id from TargetSpecs.Banks.
    /// Used by the Build Console to estimate per-bank usage before compilation.
    /// Ex: "rom" (SMS/GG/SG-1000/ColecoVision), "prg" (NES code), "chr" (NES graphics).
    /// Defaults to "rom" — override only for multi-bank targets.
    /// </summary>
    public string BankId { get; set; } = "rom";
}

/// <summary>
/// Type of a generated source file.
/// </summary>
public enum GeneratedFileType
{
    /// <summary>.c implementation file</summary>
    Source,

    /// <summary>.h header file</summary>
    Header
}