namespace Retruxel.Core.Models;

/// <summary>
/// Represents a C source file generated by a module during the build pipeline.
/// </summary>
public class GeneratedFile
{
    /// <summary>
    /// File name including extension. Ex: "physics.c", "tiles.h"
    /// </summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Full generated C source content.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// File type — determines how the CodeGenerator handles it.
    /// </summary>
    public GeneratedFileType FileType { get; set; }

    /// <summary>
    /// The module that generated this file.
    /// Used for error reporting in the ToolchainValidator.
    /// </summary>
    public string SourceModuleId { get; set; } = string.Empty;
}

/// <summary>
/// Type of a generated source file.
/// </summary>
public enum GeneratedFileType
{
    /// <summary>.c implementation file</summary>
    Source,

    /// <summary>.h header file</summary>
    Header
}