namespace Retruxel.Core.Models;

/// <summary>
/// Represents a binary asset file generated by a module during the build pipeline.
/// Ex: tile data arrays, palette tables, VGM audio data.
/// </summary>
public class GeneratedAsset
{
    /// <summary>
    /// File name including extension. Ex: "tiles.bin", "palette.bin"
    /// </summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Raw binary content of the asset.
    /// </summary>
    public byte[] Data { get; set; } = Array.Empty<byte>();

    /// <summary>
    /// Asset type — determines how the CodeGenerator embeds it in the ROM.
    /// </summary>
    public GeneratedAssetType AssetType { get; set; }

    /// <summary>
    /// The module that generated this asset.
    /// Used for error reporting in the ToolchainValidator.
    /// </summary>
    public string SourceModuleId { get; set; } = string.Empty;
}

/// <summary>
/// Type of a generated binary asset.
/// </summary>
public enum GeneratedAssetType
{
    /// <summary>Tile graphics data</summary>
    Tiles,

    /// <summary>Color palette data</summary>
    Palette,

    /// <summary>Tilemap / nametable layout data</summary>
    Tilemap,

    /// <summary>Sprite sheet data</summary>
    Sprites,

    /// <summary>Audio data — VGM, PSG register tables, etc.</summary>
    Audio,

    /// <summary>Generic binary data not covered by other types</summary>
    Raw
}