
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Entity;

/// <summary>
/// Translates the sms.entity module JSON into SMS C code using devkitSMS.
///
/// The entity module generates code that integrates with sms.physics and
/// sms.input when those modules are present in the project:
///
///   With sms.physics + sms.input (recommended):
///     sms_entity_update reads from sms_input_* functions and drives
///     sms_physics_set_vx / sms_physics_jump. Position is read from
///     sms_physics_get_x / sms_physics_get_y each frame.
///
///   Standalone (no physics/input):
///     Simple direct movement using SMS_getKeysStatus().
///     Suitable for non-physics entities like UI elements or test builds.
///
/// The CodeGen detects which mode to use via the moduleJson "usePhysics"
/// and "useInput" flags injected by the SmsTarget when both modules are
/// present in the same project. If absent, defaults to standalone mode.
///
/// Generated files:
///   entity.h — Player struct and function declarations
///   entity.c — init + update implementation
/// </summary>
public class SmsEntityCodeGen
{
    private readonly int _spriteId;
    private readonly int _x;
    private readonly int _y;
    private readonly int _speed;
    private readonly int _health;
    private readonly bool _usePhysics;
    private readonly bool _useInput;

    private const int ScreenWidth = 256;
    private const int ScreenHeight = 192;
    private const int SpriteSize = 8;

    public SmsEntityCodeGen(string moduleJson)
    {
        using var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _spriteId = root.TryGetProperty("spriteId", out var s) ? s.GetInt32() : 0;
        _x = root.TryGetProperty("x", out var x) ? x.GetInt32() : 32;
        _y = root.TryGetProperty("y", out var y) ? y.GetInt32() : 144;
        _speed = root.TryGetProperty("speed", out var sp) ? sp.GetInt32() : 2;
        _health = root.TryGetProperty("health", out var h) ? h.GetInt32() : 3;
        _usePhysics = root.TryGetProperty("usePhysics", out var up) && up.GetBoolean();
        _useInput = root.TryGetProperty("useInput", out var ui) && ui.GetBoolean();
    }

    public IEnumerable<string> Validate()
    {
        if (_x < 0 || _x >= ScreenWidth)
            yield return $"sms.entity: x={_x} is out of range (0–{ScreenWidth - 1})";
        if (_y < 0 || _y >= ScreenHeight)
            yield return $"sms.entity: y={_y} is out of range (0–{ScreenHeight - 1})";
        if (_speed < 1 || _speed > 8)
            yield return $"sms.entity: speed={_speed} is out of range (1–8)";
    }

    public GeneratedFile GenerateHeader()
    {
        var includePhysics = _usePhysics ? "\n#include \"sms_physics.h\"" : "";
        var includeInput = _useInput ? "\n#include \"sms_input.h\"" : "";

        return new GeneratedFile
        {
            FileName = "entity.h",
            FileType = GeneratedFileType.Header,
            SourceModuleId = "entity",
            Content = $$"""
                // Generated by Retruxel — sms.entity module. Do not edit manually.
                #ifndef ENTITY_H
                #define ENTITY_H
                {{includePhysics}}{{includeInput}}

                typedef struct {
                    int x;
                    int y;
                    int speed;
                    int health;
                    int spriteId;
                } Player;

                // Global player instance — accessible by sms.enemy for collision
                extern Player player;

                void entity_init(void);
                void entity_update(void);

                #endif // ENTITY_H
                """
        };
    }

    public GeneratedFile GenerateCode()
    {
        string updateBody;

        if (_usePhysics && _useInput)
        {
            // Full integration: input drives physics, physics drives position
            updateBody = $$"""
                    // Read input and drive physics
                    if (sms_input_left())  sms_physics_set_vx(-PHYS_WALK_SPEED_EXPORT);
                    else if (sms_input_right()) sms_physics_set_vx(PHYS_WALK_SPEED_EXPORT);
                    else                   sms_physics_set_vx(0);

                    if (sms_input_btn2_pressed()) sms_physics_jump();

                    // Read position from physics module
                    player.x = sms_physics_get_x();
                    player.y = sms_physics_get_y();

                    // Render sprite at physics position
                    SMS_initSprites();
                    SMS_addSprite((unsigned char)player.x, (unsigned char)player.y, (unsigned char)player.spriteId);
                    SMS_copySpritestoSAT();
                """;
        }
        else if (_useInput)
        {
            // Input module only — direct movement without physics
            updateBody = $$"""
                    if (sms_input_left())  player.x -= player.speed;
                    if (sms_input_right()) player.x += player.speed;
                    if (sms_input_up())    player.y -= player.speed;
                    if (sms_input_down())  player.y += player.speed;

                    if (player.x < 0)                                   player.x = 0;
                    if (player.x > {{ScreenWidth - SpriteSize}})         player.x = {{ScreenWidth - SpriteSize}};
                    if (player.y < 0)                                   player.y = 0;
                    if (player.y > {{ScreenHeight - SpriteSize}})         player.y = {{ScreenHeight - SpriteSize}};

                    SMS_initSprites();
                    SMS_addSprite((unsigned char)player.x, (unsigned char)player.y, (unsigned char)player.spriteId);
                    SMS_copySpritestoSAT();
                """;
        }
        else
        {
            // Standalone — direct input + movement, no modules
            updateBody = $$"""
                    unsigned int keys = SMS_getKeysStatus();

                    if (keys & PORT_A_KEY_LEFT)  player.x -= player.speed;
                    if (keys & PORT_A_KEY_RIGHT) player.x += player.speed;
                    if (keys & PORT_A_KEY_UP)    player.y -= player.speed;
                    if (keys & PORT_A_KEY_DOWN)  player.y += player.speed;

                    if (player.x < 0)                                   player.x = 0;
                    if (player.x > {{ScreenWidth - SpriteSize}})         player.x = {{ScreenWidth - SpriteSize}};
                    if (player.y < 0)                                   player.y = 0;
                    if (player.y > {{ScreenHeight - SpriteSize}})         player.y = {{ScreenHeight - SpriteSize}};

                    SMS_initSprites();
                    SMS_addSprite((unsigned char)player.x, (unsigned char)player.y, (unsigned char)player.spriteId);
                    SMS_copySpritestoSAT();
                """;
        }

        return new GeneratedFile
        {
            FileName = "entity.c",
            FileType = GeneratedFileType.Source,
            SourceModuleId = "entity",
            Content = $$"""
                // Generated by Retruxel — sms.entity module. Do not edit manually.
                // Mode: {{(_usePhysics && _useInput ? "physics+input" : _useInput ? "input only" : "standalone")}}
                #include "SMSlib.h"
                #include "entity.h"

                Player player;

                void entity_init(void) {
                    player.x        = {{_x}};
                    player.y        = {{_y}};
                    player.speed    = {{_speed}};
                    player.health   = {{_health}};
                    player.spriteId = {{_spriteId}};
                }

                void entity_update(void) {
                {{updateBody}}
                }
                """
        };
    }
}
