
using System.Text;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Logic;

/// <summary>
/// SMS code generator for the sms.physics module.
/// Generates C code for gravity, velocity and ground collision using
/// fixed-point arithmetic (positions stored as pixels × 16).
///
/// Fixed-point rationale:
///   The Z80 has no FPU and floating point is too slow for 60fps game logic.
///   Multiplying by 16 (4 fractional bits) gives enough precision for smooth
///   movement while keeping all arithmetic in 16-bit integers.
///
///   Example: groundY = 144 pixels → stored as 144 × 16 = 2304
///
/// Generated functions:
///   void          sms_physics_init(void)         — call once from main
///   void          sms_physics_update(void)       — call once per VBlank
///   void          sms_physics_set_vx(signed int vx)
///   void          sms_physics_jump(void)
///   unsigned char sms_physics_get_x(void)        — returns screen pixel X
///   unsigned char sms_physics_get_y(void)        — returns screen pixel Y
///   unsigned char sms_physics_on_ground(void)    — returns 1 if on ground
/// </summary>
public class SmsPhysicsCodeGen
{
    private readonly int _gravity;
    private readonly int _maxFallSpeed;
    private readonly int _jumpForce;
    private readonly int _walkSpeed;
    private readonly int _groundY;
    private readonly int _screenLeft;
    private readonly int _screenRight;
    private readonly int _startX;
    private readonly int _startY;

    // Fixed-point multiplier
    private const int FP = 16;

    public SmsPhysicsCodeGen(string moduleJson)
    {
        var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _gravity = root.TryGetProperty("gravity", out var g) ? g.GetInt32() : 2;
        _maxFallSpeed = root.TryGetProperty("maxFallSpeed", out var mf) ? mf.GetInt32() : 24;
        _jumpForce = root.TryGetProperty("jumpForce", out var jf) ? jf.GetInt32() : 52;
        _walkSpeed = root.TryGetProperty("walkSpeed", out var ws) ? ws.GetInt32() : 8;
        _groundY = root.TryGetProperty("groundY", out var gy) ? gy.GetInt32() : 144;
        _screenLeft = root.TryGetProperty("screenLeft", out var sl) ? sl.GetInt32() : 0;
        _screenRight = root.TryGetProperty("screenRight", out var sr) ? sr.GetInt32() : 248;
        // startX/startY come from the entity module position — default to center-ish
        _startX = root.TryGetProperty("x", out var sx) ? sx.GetInt32() : 32;
        _startY = root.TryGetProperty("y", out var sy) ? sy.GetInt32() : _groundY;
    }

    // Validation ---------------------------------------------------------------

    public IEnumerable<string> Validate()
    {
        if (_groundY > 191)
            yield return $"sms.physics: groundY={_groundY} is outside SMS screen bounds (0–191).";

        if (_screenRight > 255)
            yield return $"sms.physics: screenRight={_screenRight} exceeds SMS screen width (255).";

        if (_screenLeft >= _screenRight)
            yield return $"sms.physics: screenLeft ({_screenLeft}) must be less than screenRight ({_screenRight}).";

        if (_jumpForce <= _gravity * 4)
            yield return $"sms.physics: jumpForce={_jumpForce} may be too low relative to gravity={_gravity}. Jump might barely leave the ground.";
    }

    // Code generation ----------------------------------------------------------

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();

        // Fixed-point values for compile-time constants
        var groundYFp = _groundY * FP;
        var screenLeftFp = _screenLeft * FP;
        var screenRightFp = _screenRight * FP;
        var startXFp = _startX * FP;
        var startYFp = _startY * FP;

        sb.AppendLine("// Generated by Retruxel — sms.physics module");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("//");
        sb.AppendLine("// Fixed-point arithmetic: positions stored as pixels * 16");
        sb.AppendLine("// This avoids floating point on the Z80 while allowing sub-pixel precision.");
        sb.AppendLine("#include \"sms_physics.h\"");
        sb.AppendLine();

        // Constants
        sb.AppendLine("// Physics constants (fixed-point units unless noted)");
        sb.AppendLine($"#define PHYS_GRAVITY        {_gravity}");
        sb.AppendLine($"#define PHYS_MAX_FALL_SPEED {_maxFallSpeed}");
        sb.AppendLine($"#define PHYS_JUMP_FORCE     {_jumpForce}");
        sb.AppendLine($"#define PHYS_WALK_SPEED     {_walkSpeed}");
        sb.AppendLine($"#define PHYS_GROUND_Y       {groundYFp}    // {_groundY} pixels * {FP}");
        sb.AppendLine($"#define PHYS_SCREEN_LEFT    {screenLeftFp}    // {_screenLeft} pixels * {FP}");
        sb.AppendLine($"#define PHYS_SCREEN_RIGHT   {screenRightFp}   // {_screenRight} pixels * {FP}");
        sb.AppendLine($"#define PHYS_FP_SHIFT       4               // divide by 16 to get pixel position");
        sb.AppendLine();

        // State variables
        sb.AppendLine("// Physics state (fixed-point positions)");
        sb.AppendLine("signed int   phys_x        = 0;");
        sb.AppendLine("signed int   phys_y        = 0;");
        sb.AppendLine("signed int   phys_vx       = 0;");
        sb.AppendLine("signed int   phys_vy       = 0;");
        sb.AppendLine("unsigned char phys_grounded = 0;");
        sb.AppendLine();

        // Init — no parameters, uses values baked in at code generation time
        sb.AppendLine("// Initialize physics at the position configured in the editor");
        sb.AppendLine("void physics_init(void) {");
        sb.AppendLine($"    phys_x        = {startXFp};  // {_startX} pixels * {FP}");
        sb.AppendLine($"    phys_y        = {startYFp};  // {_startY} pixels * {FP}");
        sb.AppendLine("    phys_vx       = 0;");
        sb.AppendLine("    phys_vy       = 0;");
        sb.AppendLine("    phys_grounded = 0;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Update — gravity + velocity + collision
        sb.AppendLine("// Call once per VBlank to update position with gravity and velocity");
        sb.AppendLine("void physics_update(void) {");
        sb.AppendLine("    // Apply gravity when airborne");
        sb.AppendLine("    if (!phys_grounded) {");
        sb.AppendLine("        phys_vy += PHYS_GRAVITY;");
        sb.AppendLine("        if (phys_vy > PHYS_MAX_FALL_SPEED) {");
        sb.AppendLine("            phys_vy = PHYS_MAX_FALL_SPEED;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Apply velocity to position");
        sb.AppendLine("    phys_x += phys_vx;");
        sb.AppendLine("    phys_y += phys_vy;");
        sb.AppendLine();
        sb.AppendLine("    // Ground collision");
        sb.AppendLine("    if (phys_y >= PHYS_GROUND_Y) {");
        sb.AppendLine("        phys_y        = PHYS_GROUND_Y;");
        sb.AppendLine("        phys_vy       = 0;");
        sb.AppendLine("        phys_grounded = 1;");
        sb.AppendLine("    } else {");
        sb.AppendLine("        phys_grounded = 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Horizontal screen boundary clamp");
        sb.AppendLine("    if (phys_x < PHYS_SCREEN_LEFT)  phys_x = PHYS_SCREEN_LEFT;");
        sb.AppendLine("    if (phys_x > PHYS_SCREEN_RIGHT) phys_x = PHYS_SCREEN_RIGHT;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Set horizontal velocity
        sb.AppendLine("// Set horizontal velocity (use PHYS_WALK_SPEED, negative = left)");
        sb.AppendLine("void physics_set_vx(signed int vx) {");
        sb.AppendLine("    phys_vx = vx;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Jump
        sb.AppendLine("// Apply jump force — only if grounded");
        sb.AppendLine("void physics_jump(void) {");
        sb.AppendLine("    if (phys_grounded) {");
        sb.AppendLine("        phys_vy       = -PHYS_JUMP_FORCE;");
        sb.AppendLine("        phys_grounded  = 0;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Getters — convert fixed-point back to pixel
        sb.AppendLine("// Returns the screen pixel X position");
        sb.AppendLine("unsigned char sms_physics_get_x(void) {");
        sb.AppendLine("    return (unsigned char)(phys_x >> PHYS_FP_SHIFT);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Returns the screen pixel Y position");
        sb.AppendLine("unsigned char sms_physics_get_y(void) {");
        sb.AppendLine("    return (unsigned char)(phys_y >> PHYS_FP_SHIFT);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Returns 1 if the entity is standing on the ground");
        sb.AppendLine("unsigned char sms_physics_on_ground(void) {");
        sb.AppendLine("    return phys_grounded;");
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = "physics.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = "physics"
        };
    }

    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — sms.physics module");
        sb.AppendLine("#ifndef PHYSICS_H");
        sb.AppendLine("#define PHYSICS_H");
        sb.AppendLine();
        sb.AppendLine("// Expose walk speed so entity module can reference it");
        sb.AppendLine($"#define PHYS_WALK_SPEED_EXPORT  {_walkSpeed}");
        sb.AppendLine();
        sb.AppendLine("// Physics state (exposed for entity module)");
        sb.AppendLine("extern signed int   phys_x;");
        sb.AppendLine("extern signed int   phys_y;");
        sb.AppendLine("extern signed int   phys_vx;");
        sb.AppendLine("extern signed int   phys_vy;");
        sb.AppendLine("extern unsigned char phys_grounded;");
        sb.AppendLine();
        sb.AppendLine("void          sms_physics_init(void);");
        sb.AppendLine("void          sms_physics_update(void);");
        sb.AppendLine("void          sms_physics_set_vx(signed int vx);");
        sb.AppendLine("void          sms_physics_jump(void);");
        sb.AppendLine("unsigned char sms_physics_get_x(void);");
        sb.AppendLine("unsigned char sms_physics_get_y(void);");
        sb.AppendLine("unsigned char sms_physics_on_ground(void);");
        sb.AppendLine();
        sb.AppendLine("#endif // SMS_PHYSICS_H");

        return new GeneratedFile
        {
            FileName = "physics.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = "physics"
        };
    }
}
