
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Scroll;

/// <summary>
/// Translates the sms.scroll module JSON into SMS C code using devkitSMS.
///
/// Generated files:
///   scroll.h  — declares scroll_init() and scroll_update()
///   scroll.c  — increments/decrements the scroll offset each frame
///               and calls SMS_setScrollX()
///
/// The SMS VDP scroll register is 8-bit (0–255), wrapping naturally.
/// SMS_setScrollX(value) sets the horizontal fine scroll offset.
///
/// devkitSMS functions used:
///   SMS_setScrollX(value) — sets horizontal BG scroll offset
/// </summary>
public class SmsScrollCodeGen
{
    private readonly int _speed;
    private readonly string _direction;
    private readonly bool _loop;

    // SMS VDP scroll register wraps at 256 (full tilemap width in pixels)
    private const int ScrollWrap = 256;

    public SmsScrollCodeGen(string moduleJson)
    {
        using var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _speed = root.TryGetProperty("speed", out var sp) ? sp.GetInt32() : 1;
        _direction = root.TryGetProperty("direction", out var dir) ? dir.GetString() ?? "Left" : "Left";
        _loop = root.TryGetProperty("loop", out var lp) ? lp.GetBoolean() : true;
    }

    public GeneratedFile GenerateHeader() => new()
    {
        FileName = "scroll.h",
        FileType = GeneratedFileType.Header,
        SourceModuleId = "scroll",
        Content = """
            // Generated by Retruxel — sms.scroll module. Do not edit manually.
            #ifndef SCROLL_H
            #define SCROLL_H

            void scroll_init(void);
            void scroll_update(void);

            #endif // SCROLL_H
            """
    };

    public GeneratedFile GenerateCode()
    {
        // Left scroll: offset increases (SMS scrolls BG to the left when X increases)
        // Right scroll: offset decreases
        var delta = _direction == "Left" ? _speed : -_speed;
        var loopCode = _loop
            ? $$"""
                    /* Wrap scroll offset */
                    if (scroll_x >= {{ScrollWrap}}) scroll_x -= {{ScrollWrap}};
                    if (scroll_x < 0)             scroll_x += {{ScrollWrap}};
               """
            : $$"""
                    /* Clamp scroll offset */
                    if (scroll_x < 0)             scroll_x = 0;
                    if (scroll_x >= {{ScrollWrap}}) scroll_x = {{ScrollWrap - 1}};
               """;

        return new GeneratedFile
        {
            FileName = "scroll.c",
            FileType = GeneratedFileType.Source,
            SourceModuleId = "scroll",
            Content = $$"""
                // Generated by Retruxel — sms.scroll module. Do not edit manually.
                // Direction: {{_direction}} | Speed: {{_speed}}px/frame | Loop: {{_loop}}
                #include "SMSlib.h"
                #include "scroll.h"

                static int scroll_x;

                void scroll_init(void) {
                    scroll_x = 0;
                    SMS_setScrollX(0);
                }

                void scroll_update(void) {
                    scroll_x += {{delta}};

                {{loopCode}}

                    SMS_setScrollX((unsigned char)scroll_x);
                }
                """
        };
    }
}
