using Retruxel.Core.Models;
using System.Text;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Logic;

/// <summary>
/// SMS code generator for the sms.input module.
/// Generates C code for reading the SMS joypad with:
///   - D-pad directional state
///   - Button 1 and Button 2 tap detection (short press)
///   - Button 1 and Button 2 hold detection (long press, ≥ holdThreshold frames)
///
/// The tap/hold distinction is the core mechanic for Kung Fu Master:
///   - Button 1 tap  → punch
///   - Button 1 hold → kick (after holdThreshold frames)
///   - Button 2 tap  → jump
///   - Button 2 hold → (reserved for future use)
///
/// Generated functions:
///   void          sms_input_init(void)
///   void          sms_input_update(void)       — call once per VBlank before game logic
///   unsigned char sms_input_left(void)
///   unsigned char sms_input_right(void)
///   unsigned char sms_input_up(void)
///   unsigned char sms_input_down(void)
///   unsigned char sms_input_btn1_tap(void)     — 1 if tapped (not held)
///   unsigned char sms_input_btn2_tap(void)
///   unsigned char sms_input_btn1_held(void)    — 1 if held ≥ holdThreshold frames
///   unsigned char sms_input_btn2_held(void)
///   unsigned char sms_input_btn1_pressed(void) — 1 on the exact frame button was pressed
///   unsigned char sms_input_btn2_pressed(void)
/// </summary>
public class SmsInputCodeGen
{
    private readonly int _holdThreshold;
    private readonly int _port;

    public SmsInputCodeGen(string moduleJson)
    {
        var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _holdThreshold = root.TryGetProperty("holdThreshold", out var ht) ? ht.GetInt32() : 60;
        _port = root.TryGetProperty("port", out var p) ? p.GetInt32() : 1;
    }

    // Validation ---------------------------------------------------------------

    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        if (_holdThreshold < 10)
            errors.Add($"sms.input: holdThreshold={_holdThreshold} is very low — may cause unintended hold triggers.");

        if (_port != 1 && _port != 2)
            errors.Add($"sms.input: Invalid port={_port}. Must be 1 or 2.");

        return errors;
    }

    // Code generation ----------------------------------------------------------

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();

        // Port-specific SMSlib key constants
        var keyLeft = _port == 1 ? "PORT_A_KEY_LEFT" : "PORT_B_KEY_LEFT";
        var keyRight = _port == 1 ? "PORT_A_KEY_RIGHT" : "PORT_B_KEY_RIGHT";
        var keyUp = _port == 1 ? "PORT_A_KEY_UP" : "PORT_B_KEY_UP";
        var keyDown = _port == 1 ? "PORT_A_KEY_DOWN" : "PORT_B_KEY_DOWN";
        var keyBtn1 = _port == 1 ? "PORT_A_KEY_1" : "PORT_B_KEY_1";
        var keyBtn2 = _port == 1 ? "PORT_A_KEY_2" : "PORT_B_KEY_2";

        sb.AppendLine("// Generated by Retruxel — sms.input module");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine("#include \"sms_input.h\"");
        sb.AppendLine();

        // State variables
        sb.AppendLine("// Input state");
        sb.AppendLine("static unsigned int  keys_current  = 0;  // keys held this frame");
        sb.AppendLine("static unsigned int  keys_pressed  = 0;  // keys newly pressed this frame");
        sb.AppendLine("static unsigned char btn1_held_frames = 0;");
        sb.AppendLine("static unsigned char btn2_held_frames = 0;");
        sb.AppendLine();

        // Init
        sb.AppendLine("void sms_input_init(void) {");
        sb.AppendLine("    keys_current      = 0;");
        sb.AppendLine("    keys_pressed      = 0;");
        sb.AppendLine("    btn1_held_frames  = 0;");
        sb.AppendLine("    btn2_held_frames  = 0;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Update — call once per VBlank
        sb.AppendLine("// Call once per VBlank, before any game logic reads input");
        sb.AppendLine("void sms_input_update(void) {");
        sb.AppendLine("    keys_pressed = SMS_getKeysPressed();");
        sb.AppendLine("    keys_current = SMS_getKeysStatus();");
        sb.AppendLine();
        sb.AppendLine($"    if (keys_current & {keyBtn1}) {{");
        sb.AppendLine($"        if (btn1_held_frames < 255) btn1_held_frames++;");
        sb.AppendLine("    } else {");
        sb.AppendLine("        btn1_held_frames = 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    if (keys_current & {keyBtn2}) {{");
        sb.AppendLine($"        if (btn2_held_frames < 255) btn2_held_frames++;");
        sb.AppendLine("    } else {");
        sb.AppendLine("        btn2_held_frames = 0;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Directional inputs
        sb.AppendLine($"unsigned char sms_input_left(void)  {{ return (keys_current & {keyLeft})  ? 1 : 0; }}");
        sb.AppendLine($"unsigned char sms_input_right(void) {{ return (keys_current & {keyRight}) ? 1 : 0; }}");
        sb.AppendLine($"unsigned char sms_input_up(void)    {{ return (keys_current & {keyUp})    ? 1 : 0; }}");
        sb.AppendLine($"unsigned char sms_input_down(void)  {{ return (keys_current & {keyDown})  ? 1 : 0; }}");
        sb.AppendLine();

        // Button pressed (exact frame)
        sb.AppendLine($"unsigned char sms_input_btn1_pressed(void) {{ return (keys_pressed & {keyBtn1}) ? 1 : 0; }}");
        sb.AppendLine($"unsigned char sms_input_btn2_pressed(void) {{ return (keys_pressed & {keyBtn2}) ? 1 : 0; }}");
        sb.AppendLine();

        // Tap — pressed but not yet held
        sb.AppendLine($"// Tap: button was just pressed and not yet held for {_holdThreshold} frames");
        sb.AppendLine($"unsigned char sms_input_btn1_tap(void) {{");
        sb.AppendLine($"    return ((keys_pressed & {keyBtn1}) && btn1_held_frames < {_holdThreshold}) ? 1 : 0;");
        sb.AppendLine("}");
        sb.AppendLine($"unsigned char sms_input_btn2_tap(void) {{");
        sb.AppendLine($"    return ((keys_pressed & {keyBtn2}) && btn2_held_frames < {_holdThreshold}) ? 1 : 0;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Hold — button held for threshold frames
        sb.AppendLine($"// Held: button has been held for at least {_holdThreshold} frames (~{_holdThreshold / 60.0:F1}s at 60fps)");
        sb.AppendLine($"unsigned char sms_input_btn1_held(void) {{");
        sb.AppendLine($"    return (btn1_held_frames >= {_holdThreshold}) ? 1 : 0;");
        sb.AppendLine("}");
        sb.AppendLine($"unsigned char sms_input_btn2_held(void) {{");
        sb.AppendLine($"    return (btn2_held_frames >= {_holdThreshold}) ? 1 : 0;");
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = "sms_input.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = "sms.input"
        };
    }

    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — sms.input module");
        sb.AppendLine("#ifndef SMS_INPUT_H");
        sb.AppendLine("#define SMS_INPUT_H");
        sb.AppendLine();
        sb.AppendLine($"#define INPUT_HOLD_THRESHOLD  {_holdThreshold}");
        sb.AppendLine($"#define INPUT_PORT            {_port}");
        sb.AppendLine();
        sb.AppendLine("void          sms_input_init(void);");
        sb.AppendLine("void          sms_input_update(void);");
        sb.AppendLine();
        sb.AppendLine("unsigned char sms_input_left(void);");
        sb.AppendLine("unsigned char sms_input_right(void);");
        sb.AppendLine("unsigned char sms_input_up(void);");
        sb.AppendLine("unsigned char sms_input_down(void);");
        sb.AppendLine();
        sb.AppendLine("unsigned char sms_input_btn1_pressed(void);");
        sb.AppendLine("unsigned char sms_input_btn2_pressed(void);");
        sb.AppendLine("unsigned char sms_input_btn1_tap(void);");
        sb.AppendLine("unsigned char sms_input_btn2_tap(void);");
        sb.AppendLine("unsigned char sms_input_btn1_held(void);");
        sb.AppendLine("unsigned char sms_input_btn2_held(void);");
        sb.AppendLine();
        sb.AppendLine("#endif // SMS_INPUT_H");

        return new GeneratedFile
        {
            FileName = "sms_input.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = "sms.input"
        };
    }
}
