using Retruxel.Core.Models;
using Retruxel.Modules.Text;
using System.Text;

namespace Retruxel.Target.GG.Modules.Text;

/// <summary>
/// Game Gear-specific code generator for the text.display module.
/// Validates hardware limits: x 0-19, y 0-17 (160×144 / 8×8 tiles).
/// </summary>
public class GgTextDisplayCodeGen
{
    private const int MaxX = 19;
    private const int MaxY = 17;
    private static int _instanceCounter = 0;

    private readonly TextDisplayModule _module;
    private readonly int _instanceId;

    public static void ResetCounter() => _instanceCounter = 0;

    public GgTextDisplayCodeGen(TextDisplayModule module)
    {
        _module = module;
        _instanceId = _instanceCounter++;
    }

    /// <summary>
    /// Validates hardware limits for the GG.
    /// Returns a list of validation errors — empty if valid.
    /// </summary>
    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        if (_module.X > MaxX)
            errors.Add($"text.display: X={_module.X} exceeds GG limit ({MaxX}). Text will render off-screen.");

        if (_module.Y > MaxY)
            errors.Add($"text.display: Y={_module.Y} exceeds GG limit ({MaxY}). Text will render off-screen.");

        if (string.IsNullOrEmpty(_module.Text))
            errors.Add("text.display: Text cannot be empty.");

        return errors;
    }

    /// <summary>
    /// Generates the C code for displaying text on the GG using devkitSMS.
    /// </summary>
    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();
        var funcName = $"text_display_{_instanceId}_init";

        sb.AppendLine("// Generated by Retruxel — text.display module (GG)");
        sb.AppendLine($"#include \"text_display_{_instanceId}.h\"");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine();
        
        if (_instanceId == 0)
        {
            sb.AppendLine("const unsigned char default_palette[] = {");
            sb.AppendLine("    0x00, 0x00, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00,");
            sb.AppendLine("    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,");
            sb.AppendLine("    0x00, 0x00, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00,");
            sb.AppendLine("    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00");
            sb.AppendLine("};");
            sb.AppendLine();
        }
        
        sb.AppendLine($"void {funcName}(void) {{");
        
        if (_instanceId == 0)
        {
            sb.AppendLine("    SMS_VRAMmemsetW(0, 0x0000, 16384);");
            sb.AppendLine("    SMS_loadBGPalette(default_palette);");
            sb.AppendLine("    SMS_loadSpritePalette(default_palette);");
            sb.AppendLine("    SMS_autoSetUpTextRenderer();");
        }
        
        sb.AppendLine($"    SMS_printatXY({_module.X}, {_module.Y}, \"{_module.Text}\");");
        
        if (_instanceId == 0)
            sb.AppendLine("    SMS_displayOn();");
        
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = $"text_display_{_instanceId}.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = _module.ModuleId
        };
    }

    /// <summary>
    /// Generates the header file exposing text_display_init to other modules.
    /// </summary>
    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();
        var funcName = $"text_display_{_instanceId}_init";

        sb.AppendLine("// Generated by Retruxel — text.display module (GG)");
        sb.AppendLine($"#ifndef TEXT_DISPLAY_{_instanceId}_H");
        sb.AppendLine($"#define TEXT_DISPLAY_{_instanceId}_H");
        sb.AppendLine();
        sb.AppendLine($"void {funcName}(void);");
        sb.AppendLine();
        sb.AppendLine("#endif");

        return new GeneratedFile
        {
            FileName = $"text_display_{_instanceId}.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = _module.ModuleId
        };
    }
}