using System.IO;
using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;
using Retruxel.Core.Models.Wizard;

namespace Retruxel.Views.Wizard.Steps;

public partial class TargetStep4MainFile : UserControl
{
    private readonly TargetWizardData _data;

    public TargetStep4MainFile(TargetWizardData data)
    {
        InitializeComponent();
        _data = data;
        LoadData();
        AttachHandlers();
    }

    private void LoadData()
    {
        if (string.IsNullOrEmpty(_data.MainFileContent))
        {
            // Generate default template
            _data.MainFileContent = GenerateDefaultTemplate();
        }
        CodeTextBox.Text = _data.MainFileContent;
    }

    private void AttachHandlers()
    {
        CodeTextBox.TextChanged += (s, e) => _data.MainFileContent = CodeTextBox.Text;
    }

    private void SourceComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        // Prevent execution before InitializeComponent completes
        if (FilePickerPanel == null || CodeTextBox == null)
            return;

        var selectedIndex = SourceComboBox.SelectedIndex;
        
        switch (selectedIndex)
        {
            case 0: // Generate basic template
                FilePickerPanel.Visibility = Visibility.Collapsed;
                CodeTextBox.IsReadOnly = false;
                CodeTextBox.Text = GenerateDefaultTemplate();
                _data.MainFileSource = "template";
                break;
            
            case 1: // Type code now
                FilePickerPanel.Visibility = Visibility.Collapsed;
                CodeTextBox.IsReadOnly = false;
                CodeTextBox.Text = string.Empty;
                _data.MainFileSource = "type";
                break;
            
            case 2: // Attach existing file
                FilePickerPanel.Visibility = Visibility.Visible;
                CodeTextBox.IsReadOnly = true;
                _data.MainFileSource = "attach";
                break;
        }
    }

    private void Browse_Click(object sender, RoutedEventArgs e)
    {
        var dialog = new OpenFileDialog
        {
            Title = "Select main.c file",
            Filter = "C Files (*.c)|*.c|All Files (*.*)|*.*",
            CheckFileExists = true
        };

        if (dialog.ShowDialog() == true)
        {
            try
            {
                FilePathTextBox.Text = dialog.FileName;
                var content = File.ReadAllText(dialog.FileName);
                CodeTextBox.Text = content;
                _data.MainFileContent = content;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error reading file: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
    }

    private string GenerateDefaultTemplate()
    {
        return @"// Generated by Retruxel — do not edit manually.
// Project: {{projectName}} | Target: {{targetId}}
// Generated at: {{timestamp}}

{{includeHeaders}}

void main(void) {
    {{initCalls}}
    
    while(1) {
        {{vblankWait}}
        {{updateCalls}}
    }
}

{{embedHeaders}}
";
    }
}
