<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Retruxel.Core\Retruxel.Core.csproj" />
    <ProjectReference Include="..\..\..\Retruxel.Modules\Retruxel.Modules.csproj" />
    <ProjectReference Include="..\Retruxel.Tool.FontImporter\Retruxel.Tool.FontImporter.csproj" />
    <ProjectReference Include="..\Retruxel.Tool.LiveLink\Retruxel.Tool.LiveLink.csproj" />
  </ItemGroup>

  <Target Name="CopyToRetruxelOutput" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="..\..\..\Retruxel\bin\$(Configuration)\$(TargetFramework)\Plugins\Tools\" SkipUnchangedFiles="false" />
  </Target>

</Project>
