using System.IO;
using System.Text.Json;
using Retruxel.Core.Models.Wizard;

namespace Retruxel.Core.Services.Wizard;

/// <summary>
/// Generates Target project files from wizard data.
/// </summary>
public class TargetGenerator
{
    public void Generate(TargetWizardData data)
    {
        // Create output directory
        Directory.CreateDirectory(data.OutputPath);

        // Generate files
        GenerateTargetJson(data);
        GenerateTargetClass(data);
        GenerateMainTemplate(data);
        GenerateCsproj(data);
        GenerateReadme(data);
    }

    private void GenerateTargetJson(TargetWizardData data)
    {
        var json = new
        {
            targetId = data.TargetId,
            displayName = data.DisplayName,
            manufacturer = data.Manufacturer,
            description = data.Description,
            releaseYear = data.ReleaseYear,
            status = data.Status,
            specs = new
            {
                cpu = data.CPU,
                cpuClockHz = data.CpuClockHz,
                screenWidth = data.ScreenWidth,
                screenHeight = data.ScreenHeight,
                tileWidth = data.TileWidth,
                tileHeight = data.TileHeight,
                ramBytes = data.RamBytes,
                vramBytes = data.VramBytes,
                totalColors = data.TotalColors,
                colorDepthBitsPerChannel = data.ColorDepthBitsPerChannel,
                colorsPerPalette = data.ColorsPerPalette,
                maxSpritesOnScreen = data.MaxSpritesOnScreen,
                spritesPerScanline = data.SpritesPerScanline,
                soundChip = data.SoundChip,
                soundToneChannels = data.SoundToneChannels,
                soundNoiseChannels = data.SoundNoiseChannels
            },
            toolchain = new
            {
                compiler = data.Compiler,
                romExtension = data.RomExtension
            }
        };

        var options = new JsonSerializerOptions { WriteIndented = true };
        var jsonString = JsonSerializer.Serialize(json, options);
        File.WriteAllText(Path.Combine(data.OutputPath, "target.json"), jsonString);
    }

    private void GenerateTargetClass(TargetWizardData data)
    {
        var className = $"{data.DisplayName.Replace(" ", "")}Target";
        var template = WizardTemplateLoader.LoadTemplate("Target.cs.rtrxtemplate");
        
        var content = template
            .Replace("{{TargetId}}", data.TargetId)
            .Replace("{{DisplayName}}", data.DisplayName)
            .Replace("{{Description}}", data.Description)
            .Replace("{{ClassName}}", className)
            .Replace("{{Namespace}}", $"Retruxel.Target.{data.DisplayName.Replace(" ", "")}")
            .Replace("{{Manufacturer}}", data.Manufacturer)
            .Replace("{{CPU}}", data.CPU)
            .Replace("{{CpuClockHz}}", data.CpuClockHz.ToString())
            .Replace("{{ScreenWidth}}", data.ScreenWidth.ToString())
            .Replace("{{ScreenHeight}}", data.ScreenHeight.ToString())
            .Replace("{{TileWidth}}", data.TileWidth.ToString())
            .Replace("{{TileHeight}}", data.TileHeight.ToString())
            .Replace("{{RamBytes}}", data.RamBytes.ToString())
            .Replace("{{TotalColors}}", data.TotalColors.ToString())
            .Replace("{{ColorDepthBitsPerChannel}}", data.ColorDepthBitsPerChannel.ToString())
            .Replace("{{ColorsPerPalette}}", data.ColorsPerPalette.ToString())
            .Replace("{{MaxSpritesOnScreen}}", data.MaxSpritesOnScreen.ToString())
            .Replace("{{SpritesPerScanline}}", data.SpritesPerScanline.ToString())
            .Replace("{{SoundChip}}", data.SoundChip)
            .Replace("{{SoundToneChannels}}", data.SoundToneChannels.ToString())
            .Replace("{{SoundNoiseChannels}}", data.SoundNoiseChannels.ToString());

        File.WriteAllText(Path.Combine(data.OutputPath, $"{className}.cs"), content);
    }

    private void GenerateMainTemplate(TargetWizardData data)
    {
        var templateDir = Path.Combine(data.OutputPath, "Templates");
        Directory.CreateDirectory(templateDir);
        File.WriteAllText(Path.Combine(templateDir, "main.c.rtrx"), data.MainFileContent);
    }

    private void GenerateCsproj(TargetWizardData data)
    {
        var projectName = $"Retruxel.Target.{data.DisplayName.Replace(" ", "")}";
        var template = WizardTemplateLoader.LoadTemplate("Target.csproj.rtrxtemplate");
        
        var content = template.Replace("{{ProjectName}}", projectName);

        File.WriteAllText(Path.Combine(data.OutputPath, $"{projectName}.csproj"), content);
    }

    private void GenerateReadme(TargetWizardData data)
    {
        var content = $@"# {data.DisplayName} Target

Generated by Retruxel Target Wizard

## Next Steps

1. **Implement the Target class** (`{data.DisplayName.Replace(" ", "")}Target.cs`)
   - Implement `GetHardwarePalette()` to return the console's color palette
   - Implement `GenerateCodeForModule()` if you need custom code generation
   - Implement `GenerateMainFile()` to orchestrate the main.c generation

2. **Create a Toolchain Builder** in `Retruxel.Toolchain` project
   - Implement `IToolchainBuilder` interface
   - Register it in `ToolchainOrchestrator`
   - The generic `ToolchainAdapter` will wrap it automatically

3. **Configure the main.c template** (`Templates/main.c.rtrx`)
   - Edit the template to match your target's requirements
   - Use {{{{variables}}}} for dynamic content

4. **Build and test**
   - Build this project
   - Copy the DLL to `Retruxel/bin/Debug/net10.0/Targets/`
   - Restart Retruxel and test your target

## Target Specifications

- **Target ID:** {data.TargetId}
- **Manufacturer:** {data.Manufacturer}
- **CPU:** {data.CPU} @ {data.CpuClockHz} Hz
- **Resolution:** {data.ScreenWidth}×{data.ScreenHeight}
- **Colors:** {data.TotalColors} ({data.ColorDepthBitsPerChannel}-bit per channel)
- **Compiler:** {data.Compiler}
- **ROM Extension:** {data.RomExtension}
";

        File.WriteAllText(Path.Combine(data.OutputPath, "README.md"), content);
    }
}
