using Retruxel.Core.Models;
using System.Text;
using System.Text.Json;

namespace Retruxel.Target.SMS.Modules.Graphics;

/// <summary>
/// SMS-specific code generator for the text.display module.
/// Receives module JSON — no concrete TextDisplayModule reference.
///
/// Generated files:
///   text_display_N.h  — declares text_display_N_init()
///   text_display_N.c  — clears VRAM (instance 0 only), sets up text renderer,
///                       prints text at tile position (x, y)
///
/// SMS grid: 32 columns × 24 rows (256×192 / 8×8 tiles)
/// devkitSMS functions used:
///   SMS_VRAMmemsetW(addr, value, len)  — clears VRAM (instance 0 only)
///   SMS_autoSetUpTextRenderer()        — configures text rendering (instance 0 only)
///   SMS_printatXY(x, y, str)           — prints string at tile position
///   SMS_displayOn()                    — enables display (instance 0 only)
/// </summary>
public class SmsTextDisplayCodeGen
{
    private const int MaxX = 31;
    private const int MaxY = 23;

    private static int _instanceCounter = 0;

    private readonly int    _x;
    private readonly int    _y;
    private readonly string _text;
    private readonly int    _instanceId;

    public static void ResetCounter() => _instanceCounter = 0;

    public SmsTextDisplayCodeGen(string moduleJson)
    {
        using var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _x    = root.TryGetProperty("x",    out var xProp)    ? xProp.GetInt32()     : 0;
        _y    = root.TryGetProperty("y",    out var yProp)    ? yProp.GetInt32()     : 0;
        _text = root.TryGetProperty("text", out var textProp) ? textProp.GetString() ?? "" : "";
        _instanceId = _instanceCounter++;
    }

    public IEnumerable<string> Validate()
    {
        if (_x < 0 || _x > MaxX)
            yield return $"text.display: x={_x} exceeds SMS limit ({MaxX}). Text will render off-screen.";

        if (_y < 0 || _y > MaxY)
            yield return $"text.display: y={_y} exceeds SMS limit ({MaxY}). Text will render off-screen.";

        if (string.IsNullOrEmpty(_text))
            yield return "text.display: Text cannot be empty.";

        if (_x + _text.Length > MaxX + 1)
            yield return $"text.display: text overflows screen width " +
                         $"(x={_x} + length={_text.Length} > {MaxX + 1}).";
    }

    public GeneratedFile GenerateHeader() => new()
    {
        FileName       = $"text_display_{_instanceId}.h",
        FileType       = GeneratedFileType.Header,
        SourceModuleId = "text.display",
        Content        = $$"""
            // Generated by Retruxel — text.display module (SMS). Do not edit manually.
            #ifndef TEXT_DISPLAY_{{_instanceId}}_H
            #define TEXT_DISPLAY_{{_instanceId}}_H

            void text_display_{{_instanceId}}_init(void);

            #endif // TEXT_DISPLAY_{{_instanceId}}_H
            """
    };

    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();
        sb.AppendLine($"// Generated by Retruxel — text.display module (SMS). Do not edit manually.");
        sb.AppendLine($"#include \"text_display_{_instanceId}.h\"");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine();
        sb.AppendLine($"void text_display_{_instanceId}_init(void) {{");

        if (_instanceId == 0)
        {
            sb.AppendLine("    SMS_VRAMmemsetW(0, 0x0000, 16384);");
            sb.AppendLine("    SMS_autoSetUpTextRenderer();");
        }

        sb.AppendLine($"    SMS_printatXY({_x}, {_y}, \"{_text}\");");

        if (_instanceId == 0)
            sb.AppendLine("    SMS_displayOn();");

        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName       = $"text_display_{_instanceId}.c",
            FileType       = GeneratedFileType.Source,
            SourceModuleId = "text.display",
            Content        = sb.ToString()
        };
    }
}
