using Retruxel.Core.Engine;
using Retruxel.Core.Interfaces;
using Retruxel.Core.Models;
using System.Text;

namespace Retruxel.Target.SMS.Rendering;

/// <summary>
/// SMS-specific render backend implementation.
/// Generates C code that translates platform-agnostic render commands
/// into SMSlib function calls for Sega Master System hardware.
/// 
/// This class is used during code generation (C# side) to produce
/// the engine runtime code (C side) that will execute on the SMS.
/// 
/// Architecture: All VRAM writes go through Engine_Render().
/// Modules populate GameState, mark dirty flags, and Engine_Render
/// flushes changes to hardware during VBlank.
/// </summary>
public class SmsRenderBackend
{
    /// <summary>
    /// Generates the engine runtime header file for SMS.
    /// Contains GameState structure and function declarations.
    /// </summary>
    public GeneratedFile GenerateEngineHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — SMS Engine Runtime");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("#ifndef ENGINE_H");
        sb.AppendLine("#define ENGINE_H");
        sb.AppendLine();
        sb.AppendLine("// SDCC doesn't have stdbool.h, define bool manually");
        sb.AppendLine("#ifndef __cplusplus");
        sb.AppendLine("typedef unsigned char bool;");
        sb.AppendLine("#define true 1");
        sb.AppendLine("#define false 0");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("#ifndef NULL");
        sb.AppendLine("#define NULL ((void*)0)");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("#define MAX_TILEMAP_LAYERS 4");
        sb.AppendLine();

        // GameState structure
        sb.AppendLine("// ── Game State ────────────────────────────────────────────────");
        sb.AppendLine();
        sb.AppendLine("typedef struct {");
        sb.AppendLine("    const unsigned char* tileData;");
        sb.AppendLine("    const unsigned int* mapData;");
        sb.AppendLine("    unsigned char mapWidth;");
        sb.AppendLine("    unsigned char mapHeight;");
        sb.AppendLine("    unsigned char startTile;");
        sb.AppendLine("    unsigned char paletteIndex;");
        sb.AppendLine("    int mapX;");
        sb.AppendLine("    int mapY;");
        sb.AppendLine("    unsigned int tileDataSize;");
        sb.AppendLine("    unsigned int mapDataSize;");
        sb.AppendLine("} TilemapLayerState;");
        sb.AppendLine();

        sb.AppendLine("typedef struct {");
        sb.AppendLine("    TilemapLayerState layers[MAX_TILEMAP_LAYERS];");
        sb.AppendLine("    unsigned char layerCount;");
        sb.AppendLine("    bool dirty;");
        sb.AppendLine("} TilemapState;");
        sb.AppendLine();

        sb.AppendLine("typedef struct {");
        sb.AppendLine("    char text[256];");
        sb.AppendLine("    unsigned char x;");
        sb.AppendLine("    unsigned char y;");
        sb.AppendLine("    unsigned char color;");
        sb.AppendLine("} TextLayerState;");
        sb.AppendLine();

        sb.AppendLine("typedef struct {");
        sb.AppendLine("    unsigned char x;");
        sb.AppendLine("    unsigned char y;");
        sb.AppendLine("    unsigned char tileIndex;");
        sb.AppendLine("    bool visible;");
        sb.AppendLine("} SpriteRenderState;");
        sb.AppendLine();

        sb.AppendLine("typedef struct {");
        sb.AppendLine("    SpriteRenderState sprites[64];");
        sb.AppendLine("    unsigned char count;");
        sb.AppendLine("} SpriteLayerState;");
        sb.AppendLine();

        sb.AppendLine("typedef struct {");
        sb.AppendLine("    TilemapState tilemaps;");
        sb.AppendLine("    TextLayerState ui;");
        sb.AppendLine("    SpriteLayerState sprites;");
        sb.AppendLine();
        sb.AppendLine("    bool uiDirty;");
        sb.AppendLine("    bool spritesDirty;");
        sb.AppendLine();
        sb.AppendLine("    unsigned char scrollX;");
        sb.AppendLine("    bool scrollDirty;");
        sb.AppendLine("} GameState;");
        sb.AppendLine();

        // Function declarations
        sb.AppendLine("// ── Engine Functions ──────────────────────────────────────────");
        sb.AppendLine();
        sb.AppendLine("void Engine_Init(void);");
        sb.AppendLine("void Engine_Render(GameState* state);");
        sb.AppendLine("void Engine_ClearDirtyFlags(GameState* state);");
        sb.AppendLine();

        sb.AppendLine("#endif // ENGINE_H");

        return new GeneratedFile
        {
            FileName = "engine.h",
            FileType = GeneratedFileType.Header,
            SourceModuleId = "retruxel.engine",
            Content = sb.ToString()
        };
    }

    /// <summary>
    /// Generates the engine runtime implementation file for SMS.
    /// </summary>
    public GeneratedFile GenerateEngineSource()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Retruxel — SMS Engine Runtime");
        sb.AppendLine("// DO NOT EDIT — regenerate from the Retruxel editor");
        sb.AppendLine("#include \"engine.h\"");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine();

        // Engine_Init
        sb.AppendLine("void Engine_Init(void) {");
        sb.AppendLine("    SMS_VRAMmemsetW(0, 0x0000, 16384);");
        sb.AppendLine("    SMS_displayOn();");
        sb.AppendLine("}");
        sb.AppendLine();

        // Engine_Render
        sb.AppendLine("void Engine_Render(GameState* state) {");
        sb.AppendLine("    unsigned char i;");
        sb.AppendLine();

        // Tilemap
        sb.AppendLine("    if (state->tilemaps.dirty) {");
        sb.AppendLine("        for (i = 0; i < state->tilemaps.layerCount && i < MAX_TILEMAP_LAYERS; i++) {");
        sb.AppendLine("            TilemapLayerState* layer = &state->tilemaps.layers[i];");
        sb.AppendLine("            if (layer->tileData != NULL && layer->tileDataSize > 0) {");
        sb.AppendLine("                SMS_loadTiles(layer->tileData, layer->startTile, layer->tileDataSize);");
        sb.AppendLine("            }");
        sb.AppendLine("            if (layer->mapData != NULL && layer->mapDataSize > 0) {");
        sb.AppendLine("                SMS_loadTileMapArea(layer->mapX, layer->mapY, layer->mapData, layer->mapWidth, layer->mapHeight);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // UI text
        sb.AppendLine("    if (state->uiDirty) {");
        sb.AppendLine("        if (state->ui.text[0] != '\\0') {");
        sb.AppendLine("            SMS_printatXY(state->ui.x, state->ui.y, state->ui.text);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Sprites - ONLY flush when dirty
        sb.AppendLine("    if (state->spritesDirty) {");
        sb.AppendLine("        SMS_initSprites();");
        sb.AppendLine("        for (i = 0; i < state->sprites.count && i < 64; i++) {");
        sb.AppendLine("            SpriteRenderState* sprite = &state->sprites.sprites[i];");
        sb.AppendLine("            if (sprite->visible) {");
        sb.AppendLine("                SMS_addSprite(sprite->x, sprite->y, sprite->tileIndex);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        SMS_copySpritestoSAT();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Scroll
        sb.AppendLine("    if (state->scrollDirty) {");
        sb.AppendLine("        SMS_setBGScrollX(state->scrollX);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Engine_ClearDirtyFlags
        sb.AppendLine("void Engine_ClearDirtyFlags(GameState* state) {");
        sb.AppendLine("    state->tilemaps.dirty = false;");
        sb.AppendLine("    state->uiDirty = false;");
        sb.AppendLine("    state->spritesDirty = false;");
        sb.AppendLine("    state->scrollDirty = false;");
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = "engine.c",
            FileType = GeneratedFileType.Source,
            SourceModuleId = "retruxel.engine",
            Content = sb.ToString()
        };
    }

    public RenderBackendConstraints GetConstraints()
    {
        return new RenderBackendConstraints
        {
            MaxSprites = 64,
            MaxTiles = 448,
            ScreenWidth = 256,
            ScreenHeight = 192,
            TileWidth = 8,
            TileHeight = 8,
            MaxPaletteColors = 16,
            SupportsHardwareScroll = true,
            SupportsMultipleLayers = false
        };
    }
}
