using System.IO;
using System.Text.Json;
using Retruxel.Tool.Wizard.Models;

namespace Retruxel.Tool.Wizard.Services;

/// <summary>
/// Generates CodeGen files from wizard data.
/// </summary>
public class CodeGenGenerator
{
    public void Generate(CodeGenWizardData data)
    {
        // Create output directory
        Directory.CreateDirectory(data.OutputPath);

        // Generate files
        GenerateCodeGenJson(data);
        GenerateCodeTemplate(data);
        GenerateReadme(data);
    }

    private void GenerateCodeGenJson(CodeGenWizardData data)
    {
        var variables = data.VariableMappings.Values.Select(v => new
        {
            name = v.VariableName,
            source = v.JsonPath,
            type = v.Type,
            transformation = string.IsNullOrEmpty(v.Transformation) ? null : v.Transformation
        }).ToList();

        var json = new
        {
            moduleId = data.ModuleId,
            targetId = data.TargetId,
            displayName = data.DisplayName,
            description = data.Description,
            version = "1.0.0",
            template = "implementation.c.rtrx",
            variables = variables,
            requiredTools = data.RequiredTools.Count > 0 ? data.RequiredTools : null
        };

        var options = new JsonSerializerOptions 
        { 
            WriteIndented = true,
            DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull
        };
        
        var jsonString = JsonSerializer.Serialize(json, options);
        File.WriteAllText(Path.Combine(data.OutputPath, "codegen.json"), jsonString);
    }

    private void GenerateCodeTemplate(CodeGenWizardData data)
    {
        File.WriteAllText(Path.Combine(data.OutputPath, "implementation.c.rtrx"), data.CodeContent);
    }

    private void GenerateReadme(CodeGenWizardData data)
    {
        var content = $@"# {data.DisplayName} CodeGen

Generated by Retruxel CodeGen Wizard

## Information

- **Module ID:** {data.ModuleId}
- **Target ID:** {data.TargetId}
- **Description:** {data.Description}

## Files

- `codegen.json` - CodeGen manifest with variable mappings
- `implementation.c.rtrx` - C code template with {{{{variables}}}}

## Variables

{string.Join("\n", data.VariableMappings.Values.Select(v => 
    $"- `{{{{{v.VariableName}}}}}` → `{v.JsonPath}` ({v.Type}){(string.IsNullOrEmpty(v.Transformation) ? "" : $" [Transform: {v.Transformation}]")}"))}

## Dependencies

{(data.RequiredTools.Count > 0 ? string.Join("\n", data.RequiredTools.Select(t => $"- {t}")) : "None")}

## Installation

1. Copy this folder to `Retruxel/Plugins/CodeGens/{data.ModuleId}/{data.TargetId}/`
2. Restart Retruxel
3. The CodeGen will be automatically discovered and used when building projects

## Testing

Create a test module with the following JSON structure:

```json
{{
  ""moduleId"": ""{data.ModuleId}"",
  ""parameters"": {{
    // Add parameters that match your variable mappings
  }}
}}
```

Build a project with this module and verify the generated code.
";

        File.WriteAllText(Path.Combine(data.OutputPath, "README.md"), content);
    }
}
