using System.IO;
using Retruxel.Tool.Wizard.Models;

namespace Retruxel.Tool.Wizard.Services;

/// <summary>
/// Generates Tool project files from wizard data.
/// </summary>
public class ToolGenerator
{
    public void Generate(ToolWizardData data)
    {
        // Create output directory
        Directory.CreateDirectory(data.OutputPath);

        // Generate files
        GenerateToolClass(data);
        GenerateCsproj(data);
        GenerateReadme(data);
    }

    private void GenerateToolClass(ToolWizardData data)
    {
        var className = $"{data.DisplayName.Replace(" ", "")}Tool";
        var template = TemplateLoader.LoadTemplate("Tool.cs.rtrxtemplate");
        
        var targetIdValue = string.IsNullOrEmpty(data.TargetId) ? "null" : $"\"{data.TargetId}\"";
        var moduleIdValue = string.IsNullOrEmpty(data.ModuleId) ? "null" : $"\"{data.ModuleId}\"";
        
        var content = template
            .Replace("{{ToolId}}", data.ToolId)
            .Replace("{{DisplayName}}", data.DisplayName)
            .Replace("{{Description}}", data.Description)
            .Replace("{{Category}}", data.Category)
            .Replace("{{TargetId}}", targetIdValue)
            .Replace("{{ModuleId}}", moduleIdValue)
            .Replace("{{IsSingleton}}", data.IsSingleton.ToString().ToLower())
            .Replace("{{RequiresProject}}", data.RequiresProject.ToString().ToLower())
            .Replace("{{ClassName}}", className)
            .Replace("{{Namespace}}", $"Retruxel.Tool.{data.DisplayName.Replace(" ", "")}");

        File.WriteAllText(Path.Combine(data.OutputPath, $"{className}.cs"), content);
    }

    private void GenerateCsproj(ToolWizardData data)
    {
        var projectName = $"Retruxel.Tool.{data.DisplayName.Replace(" ", "")}";
        var template = TemplateLoader.LoadTemplate("Tool.csproj.rtrxtemplate");
        
        var content = template.Replace("{{ProjectName}}", projectName);

        File.WriteAllText(Path.Combine(data.OutputPath, $"{projectName}.csproj"), content);
    }

    private void GenerateReadme(ToolWizardData data)
    {
        var parametersSection = data.Parameters.Count > 0
            ? $@"

## Parameters

{string.Join("\n", data.Parameters.Select(p => $"- **{p.Name}** ({p.Type}): {p.Description}"))}"
            : "\n\n## Parameters\n\nThis tool has no parameters.";

        var content = $@"# {data.DisplayName} Tool

Generated by Retruxel Tool Wizard

## Information

- **Tool ID:** {data.ToolId}
- **Category:** {data.Category}
- **Target:** {(string.IsNullOrEmpty(data.TargetId) ? "Universal" : data.TargetId)}
- **Module:** {(string.IsNullOrEmpty(data.ModuleId) ? "Standalone" : data.ModuleId)}
- **Is Singleton:** {data.IsSingleton}
- **Requires Project:** {data.RequiresProject}

## Description

{data.Description}
{parametersSection}

## Next Steps

1. **Implement the Execute() method** in `{data.DisplayName.Replace(" ", "")}Tool.cs`
   - This is where your tool's main logic goes
   - Access the project via the `project` parameter (if RequiresProject is true)
   - Show UI, process files, or perform any operations needed

2. **Implement the Validate() method** (optional)
   - Add validation logic to check if the tool can run
   - Return false and set errorMessage if conditions aren't met

3. **Add an icon** (optional)
   - Set the Icon property to return an ImageSource
   - Place icon files in the project and load them

4. **Build and test**
   - Build this project
   - Copy the DLL to `Retruxel/bin/Debug/net10.0/Tools/`
   - Restart Retruxel and find your tool in the Tools menu

## Example Implementation

```csharp
public IEnumerable<string> Validate(Dictionary<string, object> input)
{{
    var errors = new List<string>();
    
    // Example validation
    if (!input.ContainsKey(""inputFile""))
        errors.Add(""Missing required parameter: inputFile"");
    
    return errors;
}}

public Dictionary<string, object> Execute(Dictionary<string, object> input)
{{
    // Extract input
    var inputFile = input[""inputFile""] as string;
    
    // Your tool logic here
    var result = ProcessFile(inputFile);
    
    // Return output
    return new Dictionary<string, object>
    {{
        {{ ""outputData"", result }},
        {{ ""success"", true }}
    }};
}}
```
";

        File.WriteAllText(Path.Combine(data.OutputPath, "README.md"), content);
    }
}
