using Retruxel.Core.Models;
using Retruxel.Modules.Text;
using System.Text;

namespace Retruxel.Target.ColecoVision.Modules.Text;

/// <summary>
/// ColecoVision-specific code generator for the text.display module.
/// Validates hardware limits: x 0-31, y 0-23 (256×192 / 8×8 tiles).
/// </summary>
public class ColecoVisionTextDisplayCodeGen
{
    private const int MaxX = 31;
    private const int MaxY = 23;
    private static int _instanceCounter = 0;

    private readonly TextDisplayModule _module;
    private readonly int _instanceId;

    public static void ResetCounter() => _instanceCounter = 0;

    public ColecoVisionTextDisplayCodeGen(TextDisplayModule module)
    {
        _module = module;
        _instanceId = _instanceCounter++;
    }

    /// <summary>
    /// Validates hardware limits for the ColecoVision.
    /// Returns a list of validation errors — empty if valid.
    /// </summary>
    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        if (_module.X > MaxX)
            errors.Add($"text.display: X={_module.X} exceeds ColecoVision limit ({MaxX}). Text will render off-screen.");

        if (_module.Y > MaxY)
            errors.Add($"text.display: Y={_module.Y} exceeds ColecoVision limit ({MaxY}). Text will render off-screen.");

        if (string.IsNullOrEmpty(_module.Text))
            errors.Add("text.display: Text cannot be empty.");

        return errors;
    }

    /// <summary>
    /// Generates the C code for displaying text on the ColecoVision using devkitSMS.
    /// </summary>
    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();
        var funcName = $"text_display_{_instanceId}_init";

        sb.AppendLine("// Generated by Retruxel — text.display module (ColecoVision)");
        sb.AppendLine($"#include \"text_display_{_instanceId}.h\"");
        sb.AppendLine("#include \"SGlib.h\"");
        sb.AppendLine();
        
        // Generate text data array
        sb.AppendLine($"const unsigned char text_data_{_instanceId}[] = {{");
        sb.Append("    ");
        for (int i = 0; i < _module.Text.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"0x{(byte)_module.Text[i]:X2}");
        }
        sb.AppendLine();
        sb.AppendLine("};");
        sb.AppendLine();
        
        sb.AppendLine($"void {funcName}(void) {{");
        
        if (_instanceId == 0)
        {
            sb.AppendLine("    SG_VRAMmemset(0x1800, 0x00, 768);");
        }
        
        var vramAddr = 0x1800 + (_module.Y * 32 + _module.X);
        sb.AppendLine($"    SG_VRAMmemcpy(0x{vramAddr:X4}, (void*)text_data_{_instanceId}, {_module.Text.Length});");
        
        if (_instanceId == 0)
            sb.AppendLine("    SG_displayOn();");
        
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = $"text_display_{_instanceId}.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = _module.ModuleId
        };
    }

    /// <summary>
    /// Generates the header file exposing text_display_init to other modules.
    /// </summary>
    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();
        var funcName = $"text_display_{_instanceId}_init";

        sb.AppendLine("// Generated by Retruxel — text.display module (ColecoVision)");
        sb.AppendLine($"#ifndef TEXT_DISPLAY_{_instanceId}_H");
        sb.AppendLine($"#define TEXT_DISPLAY_{_instanceId}_H");
        sb.AppendLine();
        sb.AppendLine($"void {funcName}(void);");
        sb.AppendLine();
        sb.AppendLine("#endif");

        return new GeneratedFile
        {
            FileName = $"text_display_{_instanceId}.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = _module.ModuleId
        };
    }
}