<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <RootNamespace>Retruxel.Tool.AudioTracker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Retruxel.Core\Retruxel.Core.csproj"/>
    <ProjectReference Include="..\..\..\..\Retruxel\Retruxel.csproj"/>
  </ItemGroup>
</Project>
