using Retruxel.Core.Models;
using System.Text.Json;

namespace Retruxel.Target.NES.Modules.Text;

/// <summary>
/// Translates the text.display module JSON into NES C code using cc65 + neslib.
///
/// Generated files:
///   text_display_N.h  — declares text_display_N_init()
///   text_display_N.c  — writes text to the NES nametable via neslib's
///                       vram_adr() + vram_write()
///
/// NES text notes:
///   - Text is rendered as tile indices in the nametable, not raw ASCII.
///   - The font CHR tiles must be loaded into pattern table by a tile module.
///   - Tile indices are assumed to map ASCII 0x20–0x7E starting at tile 0x20
///     (standard neslib font convention).
///   - vram_write() writes a byte array to VRAM — correct for strings.
///     vram_put() writes a single byte — NOT suitable for strings.
///   - VRAM writes must happen while the PPU is off (during init) or via
///     the neslib update buffer (during gameplay).
///
/// NES grid: 32 columns × 30 rows (256×240 / 8×8)
/// </summary>
public class NesTextDisplayCodeGen
{
    private readonly int    _x;
    private readonly int    _y;
    private readonly string _text;
    private readonly int    _instanceId;

    private const int MaxColumns = 32;
    private const int MaxRows    = 30;
    private static int _instanceCounter = 0;

    public static void ResetCounter() => _instanceCounter = 0;

    public NesTextDisplayCodeGen(string moduleJson)
    {
        using var doc = JsonDocument.Parse(moduleJson);
        var root = doc.RootElement;

        _x    = root.TryGetProperty("x",    out var xProp)    ? xProp.GetInt32()     : 0;
        _y    = root.TryGetProperty("y",    out var yProp)    ? yProp.GetInt32()     : 0;
        _text = root.TryGetProperty("text", out var textProp) ? textProp.GetString() ?? "" : "";
        _instanceId = _instanceCounter++;
    }

    public IEnumerable<string> Validate()
    {
        if (_x < 0 || _x >= MaxColumns)
            yield return $"text.display: x={_x} is out of range (0–{MaxColumns - 1})";

        if (_y < 0 || _y >= MaxRows)
            yield return $"text.display: y={_y} is out of range (0–{MaxRows - 1})";

        if (_x + _text.Length > MaxColumns)
            yield return $"text.display: text overflows screen width " +
                         $"(x={_x} + length={_text.Length} > {MaxColumns})";
    }

    public GeneratedFile GenerateHeader() => new()
    {
        FileName       = $"text_display_{_instanceId}.h",
        FileType       = GeneratedFileType.Header,
        SourceModuleId = "text.display",
        Content        = $$"""
            // Generated by Retruxel — text.display module. Do not edit manually.
            #ifndef TEXT_DISPLAY_{{_instanceId}}_H
            #define TEXT_DISPLAY_{{_instanceId}}_H

            // Writes the configured text to the NES nametable.
            // Call during PPU off (inside main before ppu_on_all).
            void text_display_{{_instanceId}}_init(void);

            #endif // TEXT_DISPLAY_{{_instanceId}}_H
            """
    };

    public GeneratedFile GenerateCode()
    {
        var safeText = _text.Replace("\\", "\\\\").Replace("\"", "\\\"");
        var length   = _text.Length;

        // Converte ASCII para índices de tile (subtrai 0x20)
        var tileData = string.Join(", ", _text.Select(c => $"0x{((byte)c - 0x20):X2}"));

        return new GeneratedFile
        {
            FileName       = $"text_display_{_instanceId}.c",
            FileType       = GeneratedFileType.Source,
            SourceModuleId = "text.display",
            Content        = $$"""
                // Generated by Retruxel — text.display module. Do not edit manually.
                #include "neslib.h"
                #include "text_display_{{_instanceId}}.h"

                // Text: "{{safeText}}" at ({{_x}}, {{_y}})
                static const unsigned char text_data_{{_instanceId}}[] = { {{tileData}} };

                void text_display_{{_instanceId}}_init(void) {
                    vram_adr(NTADR_A({{_x}}, {{_y}}));
                    vram_write((unsigned char *)text_data_{{_instanceId}}, {{length}});
                }
                """
        };
    }
}
