using Retruxel.Core.Models;
using Retruxel.Modules.Text;
using System.Text;

namespace Retruxel.Target.SG1000.Modules.Text;

/// <summary>
/// SG-1000-specific code generator for the text.display module.
/// Validates hardware limits: x 0-31, y 0-23 (256×192 / 8×8 tiles).
/// </summary>
public class SG1000TextDisplayCodeGen
{
    private const int MaxX = 31;
    private const int MaxY = 23;
    private static int _instanceCounter = 0;

    private readonly TextDisplayModule _module;
    private readonly int _instanceId;

    public static void ResetCounter() => _instanceCounter = 0;

    public SG1000TextDisplayCodeGen(TextDisplayModule module)
    {
        _module = module;
        _instanceId = _instanceCounter++;
    }

    /// <summary>
    /// Validates hardware limits for the SG-1000.
    /// Returns a list of validation errors — empty if valid.
    /// </summary>
    public IEnumerable<string> Validate()
    {
        var errors = new List<string>();

        if (_module.X > MaxX)
            errors.Add($"text.display: X={_module.X} exceeds SG-1000 limit ({MaxX}). Text will render off-screen.");

        if (_module.Y > MaxY)
            errors.Add($"text.display: Y={_module.Y} exceeds SG-1000 limit ({MaxY}). Text will render off-screen.");

        if (string.IsNullOrEmpty(_module.Text))
            errors.Add("text.display: Text cannot be empty.");

        return errors;
    }

    /// <summary>
    /// Generates the C code for displaying text on the SG-1000 using devkitSMS.
    /// </summary>
    public GeneratedFile GenerateCode()
    {
        var sb = new StringBuilder();
        var funcName = $"text_display_{_instanceId}_init";

        sb.AppendLine("// Generated by Retruxel — text.display module (SG-1000)");
        sb.AppendLine($"#include \"text_display_{_instanceId}.h\"");
        sb.AppendLine("#include \"SMSlib.h\"");
        sb.AppendLine();
        sb.AppendLine($"void {funcName}(void) {{");
        
        if (_instanceId == 0)
        {
            sb.AppendLine("    SMS_VRAMmemsetW(0, 0x0000, 16384);");
            sb.AppendLine("    SMS_autoSetUpTextRenderer();");
        }
        
        sb.AppendLine($"    SMS_printatXY({_module.X}, {_module.Y}, \"{_module.Text}\");");
        
        if (_instanceId == 0)
            sb.AppendLine("    SMS_displayOn();");
        
        sb.AppendLine("}");

        return new GeneratedFile
        {
            FileName = $"text_display_{_instanceId}.c",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Source,
            SourceModuleId = _module.ModuleId
        };
    }

    /// <summary>
    /// Generates the header file exposing text_display_init to other modules.
    /// </summary>
    public GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();
        var funcName = $"text_display_{_instanceId}_init";

        sb.AppendLine("// Generated by Retruxel — text.display module (SG-1000)");
        sb.AppendLine($"#ifndef TEXT_DISPLAY_{_instanceId}_H");
        sb.AppendLine($"#define TEXT_DISPLAY_{_instanceId}_H");
        sb.AppendLine();
        sb.AppendLine($"void {funcName}(void);");
        sb.AppendLine();
        sb.AppendLine("#endif");

        return new GeneratedFile
        {
            FileName = $"text_display_{_instanceId}.h",
            Content = sb.ToString(),
            FileType = GeneratedFileType.Header,
            SourceModuleId = _module.ModuleId
        };
    }
}